apiVersion: v1
kind: Service
metadata:
  name: sftp-internet
  labels:
    component: sftp-server
spec:
  type: LoadBalancer
  ports:
    - port: 2200
      targetPort: 22
      name: sftp
  selector:
    statefulset.kubernetes.io/pod-name: sftp-server-0
