resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.1/deploy/static/provider/cloud/deploy.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
