
name: 'calitp_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'calitp_warehouse'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  surrogate_key_treat_nulls_as_empty_strings: true # enable legacy behavior for dbt_utils surrogate keys, i.e. coalesce nulls to empty strings
  GTFS_SCHEDULE_START: '2021-04-16'
  PROD_GTFS_RT_START: '2022-09-15'
  INCREMENTAL_MAX_DT: ''
  'dbt_date:time_zone': 'America/Los_Angeles'
  SOURCE_DATABASE: cal-itp-data-infra # you can override with DBT_SOURCE_DATABASE env var rather than constantly using --vars

models:
  calitp_warehouse:
    schema: staging
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      schema: staging

    intermediate:
      gtfs_quality:
        guidelines_checks:
          +materialized: table

    mart:
      transit_database:
        schema: mart_transit_database
      transit_database_latest:
        schema: mart_transit_database_latest
      gtfs_quality:
        schema: mart_gtfs_quality
      gtfs:
        schema: mart_gtfs
      gtfs_schedule_latest:
        schema: mart_gtfs_schedule_latest
      ad_hoc:
        schema: mart_ad_hoc
      audit:
        schema: mart_audit
      ntd:
        schema: mart_ntd
      payments:
        +materialized: table
        schema: mart_payments
      benefits:
        schema: mart_benefits
      ntd_validation:
        schema: mart_ntd_validation
      annual_reporting:
        schema: mart_annual_reporting
      safety_and_security:
        schema: mart_safety_and_security
      ridership:
        schema: mart_ridership
