
name: 'calitp_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'calitp_warehouse'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  RT_LOOKBACK_DAYS: 30
  TRIP_UPDATES_LOOKBACK_DAYS: 7
  'dbt_date:time_zone': 'America/Los_Angeles'
  SOURCE_DATABASE: cal-itp-data-infra

models:
  calitp_warehouse:
    schema: staging
    +persist_docs:
      relation: true
      columns: true

    gtfs_schedule_latest_only:
      +materialized: table
      schema: gtfs_schedule

    gtfs_views:
      +materialized: table
      schema: views

    gtfs_views_staging:
      +materialized: view
      schema: gtfs_views_staging

    rt_views:
      +materialized: table
      schema: views

    # To-do: should probably end up in `staging`
    payments_views_staging:
      +materialized: view
      schema: payments

    # To-do: should probably end up in `mart_payments`
    payments_views:
      +materialized: table
      schema: views

    staging:
      +materialized: view
      schema: staging

    mart:
      transit_database:
        schema: mart_transit_database
      gtfs_guidelines:
        schema: mart_gtfs_guidelines
      gtfs_quality:
        schema: mart_gtfs_quality
      gtfs:
        schema: mart_gtfs
      ad_hoc:
        schema: mart_ad_hoc
