
name: 'calitp_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'calitp_warehouse'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  surrogate_key_treat_nulls_as_empty_strings: true # enable legacy behavior for dbt_utils surrogate keys, i.e. coalesce nulls to empty strings
  GTFS_SCHEDULE_START: '2021-04-16'
  PROD_GTFS_RT_START: '2022-09-15'
  INCREMENTAL_MAX_DT: ''
  'dbt_date:time_zone': 'America/Los_Angeles'
  SOURCE_DATABASE: cal-itp-data-infra # you can override with DBT_SOURCE_DATABASE env var rather than constantly using --vars

models:
  calitp_warehouse:
    schema: staging
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      schema: staging
      amplitude:
        +labels:
          domain: staging
          dataset: benefits
      audit:
        +labels:
          domain: staging
          dataset: audit
      gtfs:
        +labels:
          domain: staging
          dataset: gtfs
      gtfs_quality:
        +labels:
          domain: staging
          dataset: gtfs_quality
      ntd_annual_reporting:
        +labels:
          domain: staging
          dataset: ntd_annual_reporting
      ntd_assets:
        +labels:
          domain: staging
          dataset: ntd_assets
      ntd_funding_and_expenses:
        +labels:
          domain: staging
          dataset: ntd_funding_and_expenses
      ntd_ridership:
        +labels:
          domain: staging
          dataset: ntd_ridership
      ntd_safety_and_security:
        +labels:
          domain: staging
          dataset: ntd_safety_and_security
      ntd_validation:
        +labels:
          domain: staging
          dataset: ntd_validation
      payments:
        +labels:
          domain: staging
          dataset: payments
      rt:
        +labels:
          domain: staging
          dataset: gtfs
      state_geoportal:
        +labels:
          domain: staging
          dataset: state_geoportal
      transit_database:
        +labels:
          domain: staging
          dataset: transit_database

    intermediate:
      gtfs:
        +labels:
          domain: intermediate
          dataset: gtfs
      gtfs_quality:
        +labels:
          domain: intermediate
          dataset: gtfs_quality
        guidelines_checks:
          +materialized: table
      ntd:
        +labels:
          domain: intermediate
          dataset: ntd
      ntd_assets:
        +labels:
          domain: intermediate
          dataset: ntd_assets
      ntd_annual_reporting:
        +labels:
          domain: intermediate
          dataset: ntd_annual_reporting
      ntd_funding_and_expenses:
        +labels:
          domain: intermediate
          dataset: ntd_funding_and_expenses
      ntd_validation:
        +labels:
          domain: intermediate
          dataset: ntd_validation
      payments:
        +labels:
          domain: intermediate
          dataset: payments
      transit_database:
        +labels:
          domain: intermediate
          dataset: transit_database

    mart:
      audit:
        +labels:
          domain: mart
          dataset: audit
        schema: mart_audit
      benefits:
        +labels:
          domain: mart
          dataset: benefits
        schema: mart_benefits
      gtfs:
        +labels:
          domain: mart
          dataset: gtfs
        schema: mart_gtfs
      gtfs_quality:
        +labels:
          domain: mart
          dataset: gtfs_quality
        schema: mart_gtfs_quality
      gtfs_schedule_latest:
        +labels:
          domain: mart
          dataset: gtfs_schedule_latest
        schema: mart_gtfs_schedule_latest
      ntd:
        +labels:
          domain: mart
          dataset: ntd
        schema: mart_ntd
      ntd_annual_reporting:
        +materialized: table
        +labels:
          domain: mart
          dataset: ntd_annual_reporting
        schema: mart_ntd_annual_reporting
      ntd_assets:
        +materialized: table
        +labels:
          domain: mart
          dataset: ntd_assets
        schema: mart_ntd_assets
      ntd_funding_and_expenses:
        +materialized: table
        +labels:
          domain: mart
          dataset: ntd_funding_and_expenses
        schema: mart_ntd_funding_and_expenses
      ntd_ridership:
        +materialized: table
        +labels:
          domain: mart
          dataset: ntd_ridership
        schema: mart_ntd_ridership
      ntd_safety_and_security:
        +materialized: table
        +labels:
          domain: mart
          dataset: ntd_safety_and_security
        schema: mart_ntd_safety_and_security
      ntd_validation:
        +labels:
          domain: mart
          dataset: ntd_validation
        schema: mart_ntd_validation
      payments:
        +materialized: table
        +labels:
          domain: mart
          dataset: payments
        schema: mart_payments
      transit_database:
        +labels:
          domain: mart
          dataset: transit_database
        schema: mart_transit_database
      transit_database_latest:
        +labels:
          domain: mart
          dataset: transit_database_latest
        schema: mart_transit_database_latest
