GKE_NAME=data-infra-apps
GKE_REGION=us-west1
GKE_CHANNEL=stable
GKE_NUM_NODES=1
GKE_LOCATIONS=$GKE_REGION-a,$GKE_REGION-b,$GKE_REGION-c
GKE_MACHINE_TYPE=n1-standard-4
GKE_KUBECONFIG=$SRCDIR/kube/admin.yaml
