apiVersion: v1
kind: ConfigMap
metadata:
  name: archiver-app-vars
data:
  CALITP_AUTH_KEYS: "AC_TRANSIT_API_KEY,AMTRAK_GTFS_URL,BEAR_TRANSIT_KEY,CULVER_CITY_API_KEY,ESCALON_RT_KEY,TORRANCE_TRANSIT_API_KEY,MTC_511_API_KEY,SD_MTS_SA_API_KEY,SD_MTS_VP_TU_API_KEY,SWIFTLY_AUTHORIZATION_KEY_CALITP,WEHO_RT_KEY"
  CALITP_HUEY_REDIS_HOST: redis
  CALITP_USER: pipeline
  GOOGLE_APPLICATION_CREDENTIALS: /secrets/gtfs-feed-secrets/google_application_credentials.json
