operator: airflow.providers.google.cloud.transfers.gcs_to_gcs.GCSToGCSOperator
source_bucket: calitp-gtfs-download-config
source_object: gtfs_download_configs/dt={{ macros.ds_add(ds, -1) }}/*
destination_bucket: calitp-staging-gtfs-download-config
replace: false
source_object_required: true
