WITH source AS (
    SELECT * FROM {{ source('external_littlepay', 'device_transaction_purchases') }}
),

clean_columns_and_dedupe_files AS (
    SELECT
        {{ trim_make_empty_string_null('littlepay_transaction_id') }} AS littlepay_transaction_id,
        {{ trim_make_empty_string_null('purchase_id') }} AS purchase_id,
        {{ trim_make_empty_string_null('correlated_purchase_id') }} AS correlated_purchase_id,
        {{ trim_make_empty_string_null('product_id') }} AS product_id,
        {{ trim_make_empty_string_null('description') }} AS description,
        {{ safe_cast('indicative_amount', type_numeric()) }} AS indicative_amount,
        {{ safe_cast('transaction_time', type_timestamp()) }} AS transaction_time,
        CAST(_line_number AS INTEGER) AS _line_number,
        `instance`,
        extract_filename,
        {{ extract_littlepay_filename_ts() }} AS littlepay_export_ts,
        {{ extract_littlepay_filename_date() }} AS littlepay_export_date,
        ts,
        -- hash all content not generated by us to enable deduping full dup rows
        -- hashing at this step will preserve distinction between nulls and empty strings in case that is meaningful upstream
        {{ dbt_utils.generate_surrogate_key(['littlepay_transaction_id', 'purchase_id',
            'correlated_purchase_id', 'product_id', 'description', 'indicative_amount',
            'transaction_time']) }} AS _content_hash,
    FROM source
),

add_keys_drop_full_dupes AS (
    SELECT
        *,
        -- generate keys now that input columns have been trimmed & cast and files deduped
        {{ dbt_utils.generate_surrogate_key(['littlepay_export_ts', '_line_number', 'instance']) }} AS _key,
        {{ dbt_utils.generate_surrogate_key(['littlepay_transaction_id', 'purchase_id']) }} AS _payments_key,
    FROM clean_columns_and_dedupe_files
    {{ qualify_dedupe_full_duplicate_lp_rows() }}
),

stg_littlepay__device_transaction_purchases AS (
    SELECT
        littlepay_transaction_id,
        purchase_id,
        correlated_purchase_id,
        product_id,
        description,
        indicative_amount,
        transaction_time,
        _line_number,
        `instance`,
        extract_filename,
        littlepay_export_ts,
        littlepay_export_date,
        ts,
        _key,
        _payments_key,
        _content_hash,
    FROM add_keys_drop_full_dupes
)

SELECT * FROM stg_littlepay__device_transaction_purchases
