WITH external_kuba AS (
    {{ get_latest_dense_rank(
        external_table = source('external_kuba', 'device_properties'),
        order_by = 'ts DESC', partition_by = 'dt')
    }}
),

stg_kuba__device_properties AS (
    SELECT
        device.fo_device_logical_id AS fare_collector_device_logical_id,
        device.fo_device_type AS fare_collector_device_type,
        device.fo_device_type_model AS fare_collector_device_type_model,
        device.fo_device_serial_number AS fare_collector_device_serial_number,
        device.fo_device_description AS fare_collector_device_description,
        device.fo_device_location_id AS fare_collector_device_location_id,
        device.fo_device_location AS fare_collector_device_location,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device.fo_device_last_connection) AS fare_collector_device_last_connection,
        device_replicator_info.software_version AS device_replicator_info_software_version,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.software_last_connection) AS device_replicator_info_software_last_connection,
        device_replicator_info.cd_version AS device_replicator_info_cd_version,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.cd_last_connection) AS device_replicator_info_cd_last_connection,
        device_replicator_info.dataset_version AS device_replicator_info_dataset_version,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.dataset_last_connection) AS device_replicator_info_dataset_last_connection,
        device_replicator_info.denylist_version AS device_replicator_info_denylist_version,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.denylist_last_connection) AS device_replicator_info_deny_list_last_connection,
        device_replicator_info.acceptlist_version AS device_replicator_info_acceptlist_version,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.acceptlist_last_connection) AS device_replicator_info_accept_list_last_connection,
        device_replicator_info.binlist_version AS device_replicator_info_bin_list_version,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.binlist_last_connection) AS device_replicator_info_bin_list_last_connection,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.asset_last_connection) AS device_replicator_info_asset_last_connection,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.monitoring_last_connection) AS device_replicator_info_monitoring_last_connection,
        PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E4S000Z', device_replicator_info.ud_last_transaction_time) AS device_replicator_info_ud_last_transaction_time,
        device_monitor_info.application__isdisabled AS device_monitor_info_application_is_disabled,
        device_monitor_info.application__isinservice AS device_monitor_info_application_is_in_service,
        device_monitor_info.application__servicestatus AS device_monitor_info_application_service_status,
        device_monitor_info.gps__position.altitude AS device_monitor_info_gps_position_altitude,
        device_monitor_info.gps__position.dateTime AS device_monitor_info_gps_position_datetime,
        device_monitor_info.gps__position.direction AS device_monitor_info_gps_position_direction,
        device_monitor_info.gps__position.gpsFix AS device_monitor_info_gps_position_fix,
        device_monitor_info.gps__position.groundSpeed AS device_monitor_info_gps_position_ground_speed,
        device_monitor_info.gps__position.hasAltitude AS device_monitor_info_gps_position_has_altitude,
        device_monitor_info.gps__position.hasDateTime AS device_monitor_info_gps_position_has_datetime,
        device_monitor_info.gps__position.hasDirection AS device_monitor_info_gps_position_has_direction,
        device_monitor_info.gps__position.hasGpsFix AS device_monitor_info_gps_position_has_fix,
        device_monitor_info.gps__position.hasGroundSpeed AS device_monitor_info_gps_position_has_ground_speed,
        device_monitor_info.gps__position.hasLatitude AS device_monitor_info_gps_position_has_latitude,
        device_monitor_info.gps__position.hasLongitude AS device_monitor_info_gps_position_has_longitude,
        device_monitor_info.gps__position.latitude AS device_monitor_info_gps_position_latitude,
        device_monitor_info.gps__position.longitude AS device_monitor_info_gps_position_longitude,
        device_monitor_info.gps__position.numberSatelites AS device_monitor_info_gps_position_number_satelites,
        device_monitor_info.gps__position.properties.id AS device_monitor_info_gps_position_properties_id,
        device_monitor_info.os__uptime AS device_monitor_info_os_uptime,
        device_monitor_info.smartmedium__emv3000__batterylevel AS device_monitor_info_smart_medium_emv3000_battery_level,
        device_monitor_info.ngwifi__gps__apistatus.status AS device_monitor_info_ngwifi_gps_api_status,
        device_monitor_info.ngwifi__gps__position.altitude AS device_monitor_info_ngwifi_gps_position_altitude,
        device_monitor_info.ngwifi__gps__position.fix AS device_monitor_info_ngwifi_gps_position_fix,
        device_monitor_info.ngwifi__gps__position.heading AS device_monitor_info_ngwifi_gps_position_heading,
        device_monitor_info.ngwifi__gps__position.latitude AS device_monitor_info_ngwifi_gps_position_latitude,
        device_monitor_info.ngwifi__gps__position.longitude AS device_monitor_info_ngwifi_gps_position_longitude,
        device_monitor_info.ngwifi__gps__position.speed AS device_monitor_info_ngwifi_gps_position_speed,
        device_monitor_info.ngwifi__gps__position.success AS device_monitor_info_ngwifi_gps_position_success,
        device_monitor_info.ngwifi__gps__position.timestamp AS device_monitor_info_ngwifi_gps_position_timestamp,
        device_monitor_info.location__location__servicestatus AS device_monitor_info_location_service_status,
        device_monitor_info.location__location__source AS device_monitor_info_location_source,
        device_monitor_info.location__location__info.dataid AS device_monitor_info_location_data_id,
        device_monitor_info.location__location__info.dataversion AS device_monitor_info_location_data_version,
        device_monitor_info.location__location__info.locationProviderSource AS device_monitor_info_location_provider_source,
        device_monitor_info.location__location__info.type AS device_monitor_info_location_type,
        device_monitor_info.location__location__info.properties.id AS device_monitor_info_location_properties_id,
        device_monitor_info.location__location__info.current.zoneinfo.name AS device_monitor_info_location_current_zone_name,
        device_monitor_info.location__location__info.current.zoneinfo.reference AS device_monitor_info_location_current_zone_reference,
        device_monitor_info.location__location__info.current.stopinfo.abbreviation AS device_monitor_info_location_current_stop_abbreviation,
        device_monitor_info.location__location__info.current.stopinfo.farematrixreference AS device_monitor_info_location_current_stop_fare_matrix_reference,
        device_monitor_info.location__location__info.current.stopinfo.name AS device_monitor_info_location_current_stop_name,
        device_monitor_info.location__location__info.current.stopinfo.reference AS device_monitor_info_location_current_stop_reference,
        device_monitor_info.location__location__info.current.stopinfo.shortname AS device_monitor_info_location_current_stop_short_name,
        device_monitor_info.location__location__info.current.stopinfo.type AS device_monitor_info_location_current_stop_type,
        device_monitor_info.location__location__info.current.properties.id AS device_monitor_info_location_current_properties_id,
        dt,
        ts
    FROM external_kuba
)

SELECT * FROM stg_kuba__device_properties
