apiVersion: v1
kind: Service
metadata:
  name: sftp-intranet
  labels:
    component: sftp-server
spec:
  ports:
    - port: 22
      name: sftp
  clusterIP: None
  selector:
    component: sftp-server
