{{ config(materialized="table") }}

WITH source AS (
    SELECT * FROM {{ ref("stg_ntd_annual_data__service_by_mode_and_time_period") }}
)

SELECT {{ dbt_utils.generate_surrogate_key(['report_year', '_5_digit_ntd_id', 'type_of_service', 'mode', 'time_period']) }} as key,
       report_year,
       type_of_service,
       _5_digit_ntd_id AS ntd_id,
       agency,
       mode,
       mode_name,
       time_period,
       time_service_begins,
       time_service_ends,
       reporter_type,
       city,
       state,
       actual_vehicles_passenger_car_deadhead_hours,
       actual_vehicles_passenger_car_hours,
       actual_vehicles_passenger_car_miles,
       actual_vehicles_passenger_car_revenue_hours,
       actual_vehicles_passenger_car_revenue_miles,
       actual_vehicles_passenger_deadhead_miles,
       ada_upt,
       agency_voms,
       aptl_questionable,
       average_passenger_trip_length_aptl_,
       average_speed,
       average_speed_questionable,
       brt_non_statutory_mixed_traffic,
       charter_service_hours,
       days_of_service_operated,
       days_not_operated_strikes,
       days_not_operated_emergencies,
       deadhead_hours_questionable,
       deadhead_miles_questionable,
       directional_route_miles,
       directional_route_miles_questionable,
       mixed_traffic_right_of_way,
       mode_voms,
       mode_voms_questionable,
       organization_type,
       passenger_miles,
       passenger_miles_questionable,
       passengers_per_hour,
       passengers_per_hour_questionable,
       primary_uza_area_sq_miles,
       primary_uza_code,
       primary_uza_name,
       primary_uza_population,
       scheduled_revenue_miles_questionable,
       scheduled_vehicles_passenger_car_revenue_miles,
       school_bus_hours,
       service_area_population,
       service_area_sq_miles,
       sponsored_service_upt,
       train_deadhead_hours,
       train_deadhead_miles,
       train_hours,
       train_hours_questionable,
       trains_in_operation,
       trains_in_operation_questionable,
       train_miles,
       train_miles_questionable,
       train_revenue_hours,
       train_revenue_hours_questionable,
       train_revenue_miles,
       train_revenue_miles_questionable,
       unlinked_passenger_trips_upt,
       unlinked_passenger_trips_questionable,
       vehicle_hours_questionable,
       vehicle_miles_questionable,
       vehicle_revenue_hours_questionable,
       vehicle_revenue_miles_questionable
  FROM source
 WHERE source.time_period != "Annual Total"
