{{ config(materialized="table") }}

WITH source AS (
    SELECT * FROM {{ ref("stg_ntd__service_by_mode") }}
)

SELECT {{ dbt_utils.generate_surrogate_key(['report_year', 'ntd_id', 'type_of_service', 'mode']) }} as key,
       report_year,
       ntd_id,
       type_of_service,
       mode,
       mode_name,
       questionable_record,
       agency,
       max_agency_voms AS agency_voms,
       city,
       state,
       max_mode_voms AS mode_voms,
       max_reporter_type AS reporter_type,
       max_organization_type AS organization_type,
       max_time_period AS time_period,
       min_time_service_begins AS time_service_begins,
       max_time_service_ends AS time_service_ends,
       max_primary_uza_code AS primary_uza_code,
       max_primary_uza_name AS primary_uza_name,
       max_primary_uza_area_sq_miles AS primary_uza_area_sq_miles,
       max_primary_uza_population AS primary_uza_population,
       max_service_area_population AS service_area_population,
       max_service_area_sq_miles AS service_area_sq_miles,
       sum_days_not_operated_emergencies AS days_not_operated_emergencies,
       sum_days_not_operated_strikes AS days_not_operated_strikes,
       sum_days_of_service_operated AS days_of_service_operated,
       sum_trains_in_operation AS trains_in_operation,
       sum_ada_upt AS ada_upt,
       sum_sponsored_service_upt AS sponsored_service_upt,
       sum_unlinked_passenger_trips_upt AS unlinked_passenger_trips_upt,
       sum_actual_vehicles_passenger_car_deadhead_hours AS actual_vehicles_passenger_car_deadhead_hours,
       sum_actual_vehicles_passenger_car_hours AS actual_vehicles_passenger_car_hours,
       sum_actual_vehicles_passenger_car_revenue_hours AS actual_vehicles_passenger_car_revenue_hours,
       sum_charter_service_hours AS charter_service_hours,
       sum_school_bus_hours AS school_bus_hours,
       sum_train_deadhead_hours AS train_deadhead_hours,
       sum_train_hours AS train_hours,
       sum_train_revenue_hours AS train_revenue_hours,
       sum_actual_vehicles_passenger_car_miles AS actual_vehicles_passenger_car_miles,
       sum_actual_vehicles_passenger_car_revenue_miles AS actual_vehicles_passenger_car_revenue_miles,
       sum_actual_vehicles_passenger_deadhead_miles AS actual_vehicles_passenger_deadhead_miles,
       sum_directional_route_miles AS directional_route_miles,
       sum_passenger_miles AS passenger_miles,
       sum_scheduled_vehicles_passenger_car_revenue_miles AS scheduled_vehicles_passenger_car_revenue_miles,
       sum_train_miles AS train_miles,
       sum_train_deadhead_miles AS train_deadhead_miles,
       sum_train_revenue_miles AS train_revenue_miles
  FROM source
