{{ config(materialized='table') }}

WITH stg_transit_data_quality_issues__services AS (
    SELECT * FROM {{ ref('stg_transit_data_quality_issues__services') }}
),

dim_transit_data_quality_services AS (
    SELECT
        id,
        reporting_category__from_provider__2,
        caltrans_district__from_operating_county_geographies_,
        last_modified_time,
        public_currently_operating,
        operator,
        realtime_status,
        name,
        __alerts,
        gtfs_provider_datasets,
        gtfs_schedule_status,
        organization_type__from_provider_,
        gtfs_services_dataset,
        funding_sources,
        caltrans_district,
        gtfs_services_association,
        gtfs_dataset_publisher,
        gtfs_schedule_quality,
        __tripupdates,
        service_operator_type,
        pathways_status__from_gtfs_datasets_,
        operational_status,
        service_area_sq_miles__ntd___from_operator_,
        manual_check__gtfs_schedule_data_ingested_in_trip_planner,
        fares_v2_status,
        total_voms__ntd___from_operator_,
        manual_check__gtfs_realtime_data_ingested_in_trip_planner,
        gtfs_realtime_quality,
        __static,
        itp_id__from_provider_,
        __schedule_feeds,
        service_area_population__ntd___from_operator_,
        currently_operating,
        operating_county_geographies,
        public_currently_operating_fixed_route,
        service_type,
        provider_is_either_ntd_reporter_or_public_entity,
        website,
        operating_counties,
        provider,
        __vehiclepositions,
        is_public_entity__from_provider_,
        gtfs_dataset_producers,
        operator_organization_type,
        rider_requirements,
        service_availability_category,
        reporting_category__from_provider_,
        level_of_engagement,
        notes,
        funding_category,
        mode,
        product_components,
        avl_rti_vendor,
        avl_rti_products,
        gtfs_feedback_session_2021,
        next_steps,
        context_from_juliet,
        product__payments,
        product__from_product_components_,
        components__from_product_components_,
        itp_dataset_activities,
        alias_,
        transit_data_quality_issues_2,
        flex_status,
        service_area_type,
        service_area_buffer__miles_,
        realtime_task_todos,
        target_quarter,
        target_date__from_realtime_tasks_,
        realtime_task_status,
        realtime_tasks,
        gtfs_improvement_strategy_2021,
        paratransit_for,
        realtime_task_details,
        other__official__interactions,
        candidate_for_research,
        new_contact_info__from_usdot_,
        product__graas,
        season_start,
        season_end,
        start_date,
        organizations_2,
        eligibility_programs,
    FROM stg_transit_data_quality_issues__services
)

SELECT * FROM dim_transit_data_quality_services
