WITH staging_vehicles_type_count_by_agency AS (
    SELECT *
    FROM {{ ref('stg_ntd__vehicles_type_count_by_agency') }}
),

current_dim_organizations AS (
    SELECT
        ntd_id,
        caltrans_district
    FROM {{ ref('dim_organizations') }}
    WHERE _is_current
),

enrich_with_caltrans_district AS (
    SELECT
        staging_vehicles_type_count_by_agency.*,
        current_dim_organizations.caltrans_district
    FROM staging_vehicles_type_count_by_agency
    LEFT JOIN current_dim_organizations USING (ntd_id)
),

fct_vehicles_type_count_by_agency AS (
    SELECT *
    FROM enrich_with_caltrans_district
)

SELECT
    aerial_tram,
    aerial_tram_rptulb,
    aerial_tram_ulb,
    agency,
    agency_voms,
    articulated_bus,
    articulated_bus_ulb,
    articulated_busrptulb,
    automated_guideway_vehicle,
    automated_guideway_vehicle_1,
    automated_guideway_vehicle_2,
    automobile,
    automobile_ulb,
    automobilerptulb,
    automobiles,
    automobiles_ulb,
    bus,
    bus_ulb,
    busrptulb,
    cable_car,
    cable_car_rptulb,
    cable_car_ulb,
    city,
    commuter_rail_passenger_coach,
    commuter_rail_passenger_coach_1,
    commuter_rail_passenger_coach_2,
    commuter_rail_self_propelled,
    commuter_rail_self_propelled_1,
    commuter_rail_self_propelled_2,
    cutaway,
    cutaway_ulb,
    cutawayrptulb,
    double_decker_bus,
    double_decker_bus_ulb,
    double_decker_busrptulb,
    ferryboat,
    ferryboat_rptulb,
    ferryboat_ulb,
    heavy_rail_passenger_car,
    heavy_rail_passenger_car_1,
    heavy_rail_passenger_car_2,
    inclined_plane,
    inclined_plane_rptulb,
    inclined_plane_ulb,
    light_rail_vehicle,
    light_rail_vehicle_rptulb,
    light_rail_vehicle_ulb,
    locomotive,
    locomotive_rptulb,
    locomotive_ulb,
    minivan,
    minivan_ulb,
    minivanrptulb,
    monorail,
    monorail_ulb,
    ntd_id,
    organization_type,
    other,
    other_rptulb,
    other_ulb,
    over_the_road_bus,
    over_the_road_bus_ulb,
    over_the_road_busrptulb,
    primary_uza_population,
    report_year,
    reporter_type,
    school_bus,
    school_bus_ulb,
    schoolbusrptulb,
    sport_utility_vehicle,
    sport_utility_vehicle_rptulb,
    sport_utility_vehicle_ulb,
    state,
    steel_wheel_vehicles,
    steel_wheel_vehicles_ulb,
    streetcar,
    streetcar_rptulb,
    streetcar_ulb,
    total_revenue_vehicles,
    total_revenue_vehicles_ulb,
    total_rptulb,
    total_service_vehicles,
    total_service_vehicles_ulb,
    trolleybus,
    trolleybus_ulb,
    trolleybusrptulb,
    trucks_and_other_rubber_tire,
    trucks_and_other_rubber_tire_1,
    uace_code,
    uza_name,
    van,
    van_ulb,
    vanrptulb,
    vintage_historic_trolley,
    vintage_historic_trolley_1,
    vintage_historic_trolley_2,
    caltrans_district,
    dt,
    execution_ts
FROM fct_vehicles_type_count_by_agency
