WITH staging_vehicles_type_count_by_agency AS (
    SELECT *
    FROM {{ ref('stg_ntd__vehicles_type_count_by_agency') }}
    -- remove bad rows for 'Advance Transit, Inc. NH' and 'Southern Teton Area Rapid Transit'
    WHERE key NOT IN ('abd981f1eeb176cd71024b38c0ce24e6','0610e7c75b67e0edd77f3ef3117b15ba','ef4dab4a487ec44305b459568f3fb3f6',
        '9d4f1caeda82b63dcee955f1009b34d6')
),

dim_agency_information AS (
    SELECT
        ntd_id,
        year,
        agency_name,
        city,
        state,
        caltrans_district_current,
        caltrans_district_name_current
    FROM {{ ref('dim_agency_information') }}
),

fct_vehicles_type_count_by_agency AS (
    SELECT
        stg.key,
        stg.ntd_id,
        stg.report_year,

        agency.agency_name,
        agency.city,
        agency.state,
        agency.caltrans_district_current,
        agency.caltrans_district_name_current,

        stg.aerial_tram,
        stg.aerial_tram_rptulb,
        stg.aerial_tram_ulb,
        stg.agency_voms,
        stg.articulated_bus,
        stg.articulated_bus_ulb,
        stg.articulated_busrptulb,
        stg.automated_guideway_vehicle,
        stg.automated_guideway_vehicle_1,
        stg.automated_guideway_vehicle_2,
        stg.automobile,
        stg.automobile_ulb,
        stg.automobilerptulb,
        stg.automobiles,
        stg.automobiles_ulb,
        stg.bus,
        stg.bus_ulb,
        stg.busrptulb,
        stg.cable_car,
        stg.cable_car_rptulb,
        stg.cable_car_ulb,
        stg.commuter_rail_passenger_coach,
        stg.commuter_rail_passenger_coach_1,
        stg.commuter_rail_passenger_coach_2,
        stg.commuter_rail_self_propelled,
        stg.commuter_rail_self_propelled_1,
        stg.commuter_rail_self_propelled_2,
        stg.cutaway,
        stg.cutaway_ulb,
        stg.cutawayrptulb,
        stg.double_decker_bus,
        stg.double_decker_bus_ulb,
        stg.double_decker_busrptulb,
        stg.ferryboat,
        stg.ferryboat_rptulb,
        stg.ferryboat_ulb,
        stg.heavy_rail_passenger_car,
        stg.heavy_rail_passenger_car_1,
        stg.heavy_rail_passenger_car_2,
        stg.inclined_plane,
        stg.inclined_plane_rptulb,
        stg.inclined_plane_ulb,
        stg.light_rail_vehicle,
        stg.light_rail_vehicle_rptulb,
        stg.light_rail_vehicle_ulb,
        stg.locomotive,
        stg.locomotive_rptulb,
        stg.locomotive_ulb,
        stg.minivan,
        stg.minivan_ulb,
        stg.minivanrptulb,
        stg.monorail,
        stg.monorail_ulb,
        stg.organization_type,
        stg.other,
        stg.other_rptulb,
        stg.other_ulb,
        stg.over_the_road_bus,
        stg.over_the_road_bus_ulb,
        stg.over_the_road_busrptulb,
        stg.primary_uza_population,
        stg.reporter_type,
        stg.school_bus,
        stg.school_bus_ulb,
        stg.schoolbusrptulb,
        stg.sport_utility_vehicle,
        stg.sport_utility_vehicle_rptulb,
        stg.sport_utility_vehicle_ulb,
        stg.steel_wheel_vehicles,
        stg.steel_wheel_vehicles_ulb,
        stg.streetcar,
        stg.streetcar_rptulb,
        stg.streetcar_ulb,
        stg.total_revenue_vehicles,
        stg.total_revenue_vehicles_ulb,
        stg.total_rptulb,
        stg.total_service_vehicles,
        stg.total_service_vehicles_ulb,
        stg.trolleybus,
        stg.trolleybus_ulb,
        stg.trolleybusrptulb,
        stg.trucks_and_other_rubber_tire,
        stg.trucks_and_other_rubber_tire_1,
        stg.uace_code,
        stg.uza_name,
        stg.van,
        stg.van_ulb,
        stg.vanrptulb,
        stg.vintage_historic_trolley,
        stg.vintage_historic_trolley_1,
        stg.vintage_historic_trolley_2,
        stg.agency AS source_agency,
        stg.city AS source_city,
        stg.state AS source_state,
        stg.dt,
        stg.execution_ts
    FROM staging_vehicles_type_count_by_agency AS stg
    LEFT JOIN dim_agency_information AS agency
        ON stg.ntd_id = agency.ntd_id
            AND stg.report_year = agency.year
)

SELECT * FROM fct_vehicles_type_count_by_agency
