WITH staging_vehicles_type_count_by_agency AS (
    SELECT *
    FROM {{ ref('stg_ntd__vehicles_type_count_by_agency') }}
),

current_dim_organizations AS (
    SELECT
        ntd_id,
        caltrans_district AS caltrans_district_current,
        caltrans_district_name AS caltrans_district_name_current
    FROM {{ ref('dim_organizations_latest_with_caltrans_district') }}
),

fct_vehicles_type_count_by_agency AS (
    SELECT
        stg.aerial_tram,
        stg.aerial_tram_rptulb,
        stg.aerial_tram_ulb,
        stg.agency,
        stg.agency_voms,
        stg.articulated_bus,
        stg.articulated_bus_ulb,
        stg.articulated_busrptulb,
        stg.automated_guideway_vehicle,
        stg.automated_guideway_vehicle_1,
        stg.automated_guideway_vehicle_2,
        stg.automobile,
        stg.automobile_ulb,
        stg.automobilerptulb,
        stg.automobiles,
        stg.automobiles_ulb,
        stg.bus,
        stg.bus_ulb,
        stg.busrptulb,
        stg.cable_car,
        stg.cable_car_rptulb,
        stg.cable_car_ulb,
        stg.city,
        stg.commuter_rail_passenger_coach,
        stg.commuter_rail_passenger_coach_1,
        stg.commuter_rail_passenger_coach_2,
        stg.commuter_rail_self_propelled,
        stg.commuter_rail_self_propelled_1,
        stg.commuter_rail_self_propelled_2,
        stg.cutaway,
        stg.cutaway_ulb,
        stg.cutawayrptulb,
        stg.double_decker_bus,
        stg.double_decker_bus_ulb,
        stg.double_decker_busrptulb,
        stg.ferryboat,
        stg.ferryboat_rptulb,
        stg.ferryboat_ulb,
        stg.heavy_rail_passenger_car,
        stg.heavy_rail_passenger_car_1,
        stg.heavy_rail_passenger_car_2,
        stg.inclined_plane,
        stg.inclined_plane_rptulb,
        stg.inclined_plane_ulb,
        stg.light_rail_vehicle,
        stg.light_rail_vehicle_rptulb,
        stg.light_rail_vehicle_ulb,
        stg.locomotive,
        stg.locomotive_rptulb,
        stg.locomotive_ulb,
        stg.minivan,
        stg.minivan_ulb,
        stg.minivanrptulb,
        stg.monorail,
        stg.monorail_ulb,
        stg.ntd_id,
        stg.organization_type,
        stg.other,
        stg.other_rptulb,
        stg.other_ulb,
        stg.over_the_road_bus,
        stg.over_the_road_bus_ulb,
        stg.over_the_road_busrptulb,
        stg.primary_uza_population,
        stg.report_year,
        stg.reporter_type,
        stg.school_bus,
        stg.school_bus_ulb,
        stg.schoolbusrptulb,
        stg.sport_utility_vehicle,
        stg.sport_utility_vehicle_rptulb,
        stg.sport_utility_vehicle_ulb,
        stg.state,
        stg.steel_wheel_vehicles,
        stg.steel_wheel_vehicles_ulb,
        stg.streetcar,
        stg.streetcar_rptulb,
        stg.streetcar_ulb,
        stg.total_revenue_vehicles,
        stg.total_revenue_vehicles_ulb,
        stg.total_rptulb,
        stg.total_service_vehicles,
        stg.total_service_vehicles_ulb,
        stg.trolleybus,
        stg.trolleybus_ulb,
        stg.trolleybusrptulb,
        stg.trucks_and_other_rubber_tire,
        stg.trucks_and_other_rubber_tire_1,
        stg.uace_code,
        stg.uza_name,
        stg.van,
        stg.van_ulb,
        stg.vanrptulb,
        stg.vintage_historic_trolley,
        stg.vintage_historic_trolley_1,
        stg.vintage_historic_trolley_2,

        orgs.caltrans_district_current,
        orgs.caltrans_district_name_current,

        stg.dt,
        stg.execution_ts
    FROM staging_vehicles_type_count_by_agency AS stg
    LEFT JOIN current_dim_organizations AS orgs USING (ntd_id)
    WHERE stg.state = 'CA'
)

SELECT * FROM fct_vehicles_type_count_by_agency
