operator: operators.ExternalTable
bucket: "{{ env_var('CALITP_BUCKET__LITTLEPAY_PARSED_V3') }}"
source_objects:
  - "products/*.jsonl.gz"
destination_project_dataset_table: "external_littlepay.products_v3"
source_format: NEWLINE_DELIMITED_JSON
use_bq_client: true
hive_options:
  mode: CUSTOM
  require_partition_filter: false
  source_uri_prefix: "products/{instance:STRING}/{extract_filename:STRING}/{ts:TIMESTAMP}/"
schema_fields:
  - name: participant_id
    type: STRING
  - name: product_id
    type: STRING
  - name: previous_version_id
    type: STRING
  - name: original_version_id
    type: STRING
  - name: product_code
    type: STRING
  - name: product_description
    type: STRING
  - name: product_type
    type: STRING  # (Capping, Discount)
  - name: activation_type
    type: STRING  # (Customer, Card)
  - name: product_status
    type: STRING  # (Active, Inactive)
  - name: superseded
    type: STRING
  - name: product_created_timestamp_utc # renamed in v3 from created_date
    type: STRING
  - name: capping_type
    type: STRING  # (Daily_cap, Weekly_cap, Multiday_cap, Timebased_cap)
  - name: multi_operator
    type: STRING
  - name: capping_start_time
    type: STRING
  - name: capping_end_time
    type: STRING
  - name: rules_transaction_types
    type: STRING  # (Autoscan, Flat, Variable)
  - name: rules_default_limit
    type: STRING
  - name: rules_max_fare_value
    type: STRING
  - name: scheduled_start_timestamp_utc # renamed in v3 from scheduled_start_date_time
    type: TIMESTAMP
  - name: scheduled_end_timestamp_utc # renamed in v3 from scheduled_end_date_time
    type: TIMESTAMP
  - name: all_day
    type: BOOLEAN
  - name: weekly_cap_start_day
    type: STRING  # (Monday, Sunday)
  - name: weekly_cap_end_day
    type: STRING
  - name: number_of_days_in_cap_window
    type: STRING
  - name: capping_duration
    type: STRING
  - name: number_of_transfer
    type: STRING
  - name: capping_time_zone
    type: STRING
  - name: capping_overlap_time
    type: STRING
  - name: capping_application_level
    type: STRING  # (Customer, Card)
  - name: route_capping_enabled
    type: STRING
  - name: routes
    type: STRING
  - name: zoned_capping_enabled
    type: BOOLEAN
  - name: zoned_capping_mode
    type: STRING
  - name: zoned_capping_pricing_type
    type: STRING
  - name: on_peak_zones
    type: STRING
  - name: off_peak_zones
    type: STRING
  - name: incentive_enabled
    type: BOOLEAN
  - name: incentive_type
    type: STRING
  - name: discount_qualifier
    type: STRING
  - name: configuration
    type: STRING
  - name: record_updated_timestamp_utc
    type: TIMESTAMP
  - name: channel
    type: STRING
  - name: _line_number
    type: STRING
