WITH source AS (
    SELECT * FROM {{ source('ntd_data_products', 'annual_database_agency_information') }}
),

stg_ntd__annual_database_agency_information AS (
    SELECT
        year,
        ntd_id,
        state_parent_ntd_id,
        agency_name,
        reporter_acronym,
        doing_business_as,
        division_department,
        legacy_ntd_id,
        reported_by_ntd_id,
        reported_by_name,
        reporter_type,
        reporting_module,
        organization_type,
        subrecipient_type,
        fy_end_date,
        original_due_date,
        address_line_1,
        address_line_2,
        p_o__box,
        city,
        state,
        zip_code,
        zip_code_ext,
        region,
        url,
        fta_recipient_id,
        ueid,
        service_area_sq_miles,
        service_area_pop,
        primary_uza AS primary_uza_code,
        uza_name AS primary_uza_name,
        tribal_area_name,
        population,
        density,
        sq_miles,
        voms_do,
        voms_pt,
        total_voms,
        volunteer_drivers,
        personal_vehicles,
        tam_tier,
        number_of_state_counties,
        number_of_counties_with_service,
        state_admin_funds_expended,
        dt,
        ts
    FROM source
)

SELECT * FROM stg_ntd__annual_database_agency_information
