WITH source AS (
    SELECT * FROM {{ source('external_littlepay_v3', 'authorisations') }}
),

clean_columns AS (
    SELECT
        {{ trim_make_empty_string_null('participant_id') }} AS participant_id,
        {{ trim_make_empty_string_null('aggregation_id') }} AS aggregation_id,

        -- renamed acquirer_code in v3, this was acquirer_id in v1
        {{ trim_make_empty_string_null('acquirer_code') }} AS acquirer_id,
        {{ trim_make_empty_string_null('request_type') }} AS request_type,

        -- renamed amount in v3, this was transaction_amount in v1
        {{ safe_cast('amount', type_numeric()) }} AS transaction_amount,
        {{ safe_cast('currency_code', type_int()) }} AS currency_code,
        {{ trim_make_empty_string_null('retrieval_reference_number') }} AS retrieval_reference_number,
        {{ trim_make_empty_string_null('littlepay_reference_number') }} AS littlepay_reference_number,
        {{ trim_make_empty_string_null('external_reference_number') }} AS external_reference_number,
        {{ trim_make_empty_string_null('response_code') }} AS response_code,
        {{ trim_make_empty_string_null('status') }} AS status,

        -- renamed authorisation_timestamp_utc in v3, this was authorisation_date_time_utc in v1
        {{ safe_cast('authorisation_timestamp_utc', type_timestamp()) }} AS authorisation_date_time_utc,
        CAST(_line_number AS INTEGER) AS _line_number,
        `instance`,
        extract_filename,
        {{ extract_littlepay_filename_ts() }} AS littlepay_export_ts,
        {{ extract_littlepay_filename_date() }} AS littlepay_export_date,

        -- these are new fields in v3, excluding for now to faciliate union with feed v1
        -- request_created_timestamp_utc,
        -- record_updated_timestamp_utc,
        -- channel,

        ts,
        -- hash all content not generated by us to enable deduping full dup rows
        -- hashing at this step will preserve distinction between nulls and empty strings in case that is meaningful upstream
        {{ dbt_utils.generate_surrogate_key(['participant_id',
            'aggregation_id', 'acquirer_code', 'request_type', 'amount', 'currency_code',
            'retrieval_reference_number', 'littlepay_reference_number', 'external_reference_number',
            'response_code', 'status', 'authorisation_timestamp_utc']) }} AS _content_hash,
    FROM source
    -- drop extra header rows
    WHERE aggregation_id != "aggregation_id"
),

add_keys_drop_full_dupes AS (
    SELECT
        *,
        -- generate keys now that input columns have been trimmed & cast
        {{ dbt_utils.generate_surrogate_key(['littlepay_export_ts', '_line_number', 'instance']) }} AS _key,
        {{ dbt_utils.generate_surrogate_key(['aggregation_id', 'authorisation_date_time_utc']) }} AS _payments_key,
    FROM clean_columns
    {{ qualify_dedupe_full_duplicate_lp_rows() }}
),

-- we have some authorisations where the same aggregation has multiple rows with the same timestamp
-- these seem like clear duplicates, and some of them one of the two copies is missing status and RRN; these can be dropped
-- the rest need to be handled downstream by checking against settlements data
same_timestamp_simple_dupes AS (
    SELECT
        _payments_key,
        (COUNT(DISTINCT retrieval_reference_number) = 1 AND COUNT(*) > 1) AS drop_candidate,
    FROM add_keys_drop_full_dupes
    GROUP BY 1
),

stg_littlepay__authorisations_v3 AS (
    SELECT
        participant_id,
        aggregation_id,
        acquirer_id,
        request_type,
        transaction_amount,
        currency_code,
        retrieval_reference_number,
        littlepay_reference_number,
        external_reference_number,
        response_code,
        status,
        authorisation_date_time_utc,
         _line_number,
        `instance`,
        extract_filename,
        littlepay_export_ts,
        littlepay_export_date,

        -- these are new fields in v3, excluding for now to faciliate union with feed v1
        -- request_created_timestamp_utc,
        -- record_updated_timestamp_utc,
        -- channel,

        ts,
        _key,
        _payments_key,
        _content_hash,
    FROM add_keys_drop_full_dupes
    LEFT JOIN same_timestamp_simple_dupes
    USING(_payments_key)
    -- rows to drop are those where RRN is null and it's a duplicate
    WHERE NOT drop_candidate OR retrieval_reference_number IS NOT NULL
)

SELECT * FROM stg_littlepay__authorisations_v3
