WITH source AS (
    SELECT * FROM {{ source('external_littlepay_v3', 'terminal_device_transactions') }}
),

clean_columns AS (
    SELECT
        {{ trim_make_empty_string_null('littlepay_transaction_id') }} AS littlepay_transaction_id,
        {{ trim_make_empty_string_null('participant_id') }} AS participant_id,
        {{ trim_make_empty_string_null('customer_id') }} AS customer_id,
        {{ trim_make_empty_string_null('funding_source_id') }} AS funding_source_id,
        {{ safe_cast('transaction_timestamp_utc', type_timestamp()) }} AS transaction_timestamp_utc,
        {{ trim_make_empty_string_null('transaction_outcome') }} AS transaction_outcome,
        {{ safe_cast('terminal_denied', type_boolean()) }} AS terminal_denied,
        {{ safe_cast('record_updated_timestamp_utc', type_timestamp()) }} AS record_updated_timestamp_utc,
        {{ trim_make_empty_string_null('channel') }} AS channel,
        CAST(_line_number AS INTEGER) AS _line_number,
        `instance`,
        extract_filename,
        ts,
        {{ extract_littlepay_filename_ts() }} AS littlepay_export_ts,
        {{ extract_littlepay_filename_date() }} AS littlepay_export_date,
        -- hash all content not generated by us to enable deduping full dup rows
        -- hashing at this step will preserve distinction between nulls and empty strings in case that is meaningful upstream
        {{ dbt_utils.generate_surrogate_key(['littlepay_transaction_id', 'participant_id', 'customer_id',
            'funding_source_id', 'transaction_timestamp_utc', 'transaction_outcome', 'terminal_denied',
            'record_updated_timestamp_utc', 'channel']) }} AS _content_hash,
    FROM source
),

add_keys_drop_full_dupes AS (
    SELECT
        *,
        -- generate keys now that input columns have been trimmed & cast and files deduped
        {{ dbt_utils.generate_surrogate_key(['littlepay_export_ts', '_line_number', 'instance']) }} AS _key,
        {{ dbt_utils.generate_surrogate_key(['littlepay_transaction_id']) }} AS _payments_key,
    FROM clean_columns
    {{ qualify_dedupe_full_duplicate_lp_rows() }}
),

stg_littlepay__terminal_device_transactions_v3 AS (
    SELECT
        littlepay_transaction_id,
        participant_id,
        customer_id,
        funding_source_id,
        transaction_timestamp_utc,
        transaction_outcome,
        terminal_denied,
        record_updated_timestamp_utc,
        channel,
        _line_number,
        `instance`,
        extract_filename,
        ts,
        littlepay_export_ts,
        littlepay_export_date,
        _content_hash,
        _key,
        _payments_key
    FROM add_keys_drop_full_dupes
)

SELECT * FROM stg_littlepay__terminal_device_transactions_v3
