{{ config(schema='views', materialized='table') }}

SELECT
  amplitude_id,
  app,
  city,
  client_event_time,
  client_upload_time,
  country,
  device_family,
  device_id,
  device_type,
  event_id,
  event_properties.language AS event_properties_language,
  event_properties.path AS event_properties_path,
  event_properties.provider_name AS event_properties_provider_name,
  event_properties.status AS event_properties_status,
  event_time,
  event_type,
  language,
  processed_time,
  schema,
  server_received_time,
  server_upload_time,
  session_id,
  user_creation_time,
  user_id,
  user_properties.provider_name AS user_properties_provider_name,
  user_properties.referrer AS user_properties_referrer,
  user_properties.referring_domain AS user_properties_referring_domain,
  user_properties.user_agent AS user_properties_user_agent,
  uuid,
  version_name,
FROM
    {{ source('amplitude', 'benefits_events') }}
