# generated by datamodel-codegen:
#   filename:  https://schemas.getdbt.com/dbt/sources/v3.json
#   timestamp: 2023-05-02T16:20:21+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra, Field


class FreshnessMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    dbt_schema_version: Optional[str] = "https://schemas.getdbt.com/dbt/sources/v3.json"
    dbt_version: Optional[str] = "1.0.0b2"
    generated_at: Optional[datetime] = "2021-11-02T20:18:06.796684Z"
    invocation_id: Optional[str] = None
    env: Optional[Dict[str, str]] = {}


class Status(Enum):
    runtime_error = "runtime error"


class SourceFreshnessRuntimeError(BaseModel):
    class Config:
        extra = Extra.forbid

    unique_id: str
    error: Optional[Union[str, int]] = None
    status: Status


class Status1(Enum):
    pass_ = "pass"
    warn = "warn"
    error = "error"
    runtime_error = "runtime error"


class PeriodEnum(Enum):
    minute = "minute"
    hour = "hour"
    day = "day"


class Time(BaseModel):
    class Config:
        extra = Extra.forbid

    count: Optional[int] = None
    period: Optional[PeriodEnum] = None


class TimingInfo(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


class FreshnessThreshold(BaseModel):
    class Config:
        extra = Extra.forbid

    warn_after: Optional[Time] = Field(
        default_factory=lambda: Time.parse_obj({"count": None, "period": None})
    )
    error_after: Optional[Time] = Field(
        default_factory=lambda: Time.parse_obj({"count": None, "period": None})
    )
    filter: Optional[str] = None


class SourceFreshnessOutput(BaseModel):
    class Config:
        extra = Extra.forbid

    unique_id: str
    max_loaded_at: datetime
    snapshotted_at: datetime
    max_loaded_at_time_ago_in_s: float
    status: Status1
    criteria: FreshnessThreshold
    adapter_response: Dict[str, Any]
    timing: List[TimingInfo]
    thread_id: str
    execution_time: float


class Model(BaseModel):
    class Config:
        extra = Extra.forbid

    metadata: FreshnessMetadata
    results: List[Union[SourceFreshnessRuntimeError, SourceFreshnessOutput]]
    elapsed_time: float
