"""Regenerate the [tool.uv] constraint-dependencies block in pyproject.toml.

Reads `pip freeze` output from the Composer image on stdin (see the
`composer-constraints` Makefile target) and pins every package to the version
the image ships, so local tests resolve to what runs in Composer. Packages
pinned in requirements-c3.txt take precedence, since Composer installs those
on top of the image.
"""

import pathlib
import re
import sys

AIRFLOW_DIR = pathlib.Path(__file__).resolve().parent.parent
PYPROJECT = AIRFLOW_DIR / "pyproject.toml"
REQUIREMENTS_C3 = AIRFLOW_DIR / "requirements-c3.txt"
BEGIN = "    # BEGIN generated by `make composer-constraints`\n"
END = "    # END generated by `make composer-constraints`\n"


def normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def version_from_url(url: str) -> str | None:
    """Version from a `name @ file:///.../<wheel or sdist>` freeze entry."""
    filename = url.split("#")[0].rsplit("/", 1)[-1]
    if filename.endswith(".whl"):
        return filename.split("-")[1]
    for extension in (".tar.gz", ".zip"):
        if filename.endswith(extension):
            return filename[: -len(extension)].rsplit("-", 1)[1]
    return None


def parse_pins(lines) -> dict[str, str]:
    pins = {}
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "==" in line:
            name, version = line.split("==", 1)
        elif " @ " in line:
            name, url = line.split(" @ ", 1)
            version = version_from_url(url)
            if version is None:
                print(f"skipping {line}", file=sys.stderr)
                continue
        else:
            continue
        # drop local version labels (the image's Airflow is "2.10.5+composer"),
        # which don't exist on PyPI; "==2.10.5" still matches the image
        pins[normalize(name)] = version.strip().split("+", 1)[0]
    return pins


def main() -> None:
    pins = parse_pins(sys.stdin)
    if "apache-airflow" not in pins:
        sys.exit("no apache-airflow version in input; is this a Composer image?")
    pins |= parse_pins(REQUIREMENTS_C3.read_text().splitlines())

    block = "".join(f'    "{name}=={pins[name]}",\n' for name in sorted(pins))
    text = PYPROJECT.read_text()
    start, end = text.index(BEGIN) + len(BEGIN), text.index(END)
    PYPROJECT.write_text(text[:start] + block + text[end:])
    print(f"wrote {len(pins)} constraints to {PYPROJECT}", file=sys.stderr)


if __name__ == "__main__":
    main()
