{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        partition_by = {
            'field': 'dt',
            'data_type': 'date',
            'granularity': 'day',
        },
    )
}}

WITH fct_kuba__device_properties AS(
    SELECT fare_collector_device_logical_id,
           fare_collector_device_type,
           fare_collector_device_type_model,
           fare_collector_device_serial_number,
           fare_collector_device_description,
           fare_collector_device_location_id,
           fare_collector_device_location,
           fare_collector_device_last_connection,
           device_replicator_info_software_version,
           device_replicator_info_software_last_connection,
           device_replicator_info_cd_version,
           device_replicator_info_cd_last_connection,
           device_replicator_info_dataset_version,
           device_replicator_info_dataset_last_connection,
           device_replicator_info_denylist_version,
           device_replicator_info_deny_list_last_connection,
           device_replicator_info_acceptlist_version,
           device_replicator_info_accept_list_last_connection,
           device_replicator_info_bin_list_version,
           device_replicator_info_bin_list_last_connection,
           device_replicator_info_asset_last_connection,
           device_replicator_info_monitoring_last_connection,
           device_replicator_info_ud_last_transaction_time,
           device_monitor_info_application_is_disabled,
           device_monitor_info_application_is_in_service,
           device_monitor_info_application_service_status,
           device_monitor_info_gps_position_altitude,
           device_monitor_info_gps_position_datetime,
           device_monitor_info_gps_position_direction,
           device_monitor_info_gps_position_fix,
           device_monitor_info_gps_position_ground_speed,
           device_monitor_info_gps_position_has_altitude,
           device_monitor_info_gps_position_has_datetime,
           device_monitor_info_gps_position_has_direction,
           device_monitor_info_gps_position_has_fix,
           device_monitor_info_gps_position_has_ground_speed,
           device_monitor_info_gps_position_has_latitude,
           device_monitor_info_gps_position_has_longitude,
           device_monitor_info_gps_position_latitude,
           device_monitor_info_gps_position_longitude,
           device_monitor_info_gps_position_number_satelites,
           device_monitor_info_gps_position_properties_id,
           device_monitor_info_os_uptime,
           device_monitor_info_smart_medium_emv3000_battery_level,
           device_monitor_info_ngwifi_gps_api_status,
           device_monitor_info_ngwifi_gps_position_altitude,
           device_monitor_info_ngwifi_gps_position_fix,
           device_monitor_info_ngwifi_gps_position_heading,
           device_monitor_info_ngwifi_gps_position_latitude,
           device_monitor_info_ngwifi_gps_position_longitude,
           device_monitor_info_ngwifi_gps_position_speed,
           device_monitor_info_ngwifi_gps_position_success,
           device_monitor_info_ngwifi_gps_position_timestamp,
           device_monitor_info_location_service_status,
           device_monitor_info_location_source,
           device_monitor_info_location_data_id,
           device_monitor_info_location_data_version,
           device_monitor_info_location_provider_source,
           device_monitor_info_location_type,
           device_monitor_info_location_properties_id,
           device_monitor_info_location_current_zone_name,
           device_monitor_info_location_current_zone_reference,
           device_monitor_info_location_current_stop_abbreviation,
           device_monitor_info_location_current_stop_fare_matrix_reference,
           device_monitor_info_location_current_stop_name,
           device_monitor_info_location_current_stop_reference,
           device_monitor_info_location_current_stop_short_name,
           device_monitor_info_location_current_stop_type,
           device_monitor_info_location_current_properties_id,
           dt,
           ts
      FROM {{ ref('stg_kuba__device_properties') }}
     WHERE {{ incremental_where(default_start_var='KUBA_DEVICE_START') | trim }}
)

SELECT * FROM fct_kuba__device_properties
