apiVersion: v2
name: jupyterhub
description: JupyterHub for Kubernetes
type: application
version: 0.1.0
appVersion: "4.1.5"
dependencies:
  - name: jupyterhub
    version: 3.3.7
    repository: https://jupyterhub.github.io/helm-chart
