# These values as applied first as template-provided defaults

deploymentStrategy:
  type: Recreate

admin:

  # by configuring an existing secret, a random one will not be generated
  existingSecret: grafana-initial-admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:

      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring-prometheus.svc.cluster.local
        isDefault: true

dashboardProviders:

  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:

  default:

    node-exporter:
      gnetId: 1860
      revision: 22
      datasource: Prometheus

    workload-view:
      gnetId: 8588
      revision: 1
      datasource: Prometheus

    cluster-view:
      gnetId: 7249
      revision: 1
      datasource: Prometheus

    ingress-nginx:
      gnetId: 9614
      revision: 1
      datasource: Prometheus

    ingress-nginx-daemonset:
      gnetId: 13736
      revision: 1
      datasource: Prometheus



persistence:

  enabled: true

ingress:

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
