cronjob:
  image: ghcr.io/jarvusinnovations/restic-toolkit:1.3.0

secretMounts:
  - name: database-backup
    mountPath: /secrets/database-backup

config:
  envFrom:
    - secretRef:
        name: database-backup
  env:
    - name: GOOGLE_PROJECT_ID
      value: '1005246706141'
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secrets/database-backup/gcs-upload-svcacct.json
    - name: PGPORT
      value: '5432'
    - name: PGDATABASE
      value: 'sentry' # by sentry helm chart
    - name: PGUSER
      value: 'postgres' # by sentry helm chart
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: sentry-sentry-postgresql
          key: postgresql-password
    - name: RESTIC_REPOSITORY
      value: gs:calitp-backups-sentry:/
    - name: PGHOST
      value: sentry-sentry-postgresql.sentry.svc.cluster.local

healthchecks:
  uuid: 93c6d460-e014-4b30-bf32-b7974bf5fa4d
