resource "google_compute_forwarding_rule" "tfer--a0d3bb39e959b49a1b6015fd2193e30d" {
  all_ports               = "false"
  allow_global_access     = "false"
  allow_psc_global_access = "false"
  description             = "{\"kubernetes.io/service-name\":\"prod-sftp-ingest-elavon/sftp-internet\"}"
  ip_address              = "34.145.56.125"
  ip_protocol             = "TCP"
  is_mirroring_collector  = "false"
  load_balancing_scheme   = "EXTERNAL"
  name                    = "a0d3bb39e959b49a1b6015fd2193e30d"
  network_tier            = "PREMIUM"
  port_range              = "2200-2200"
  project                 = "cal-itp-data-infra"
  recreate_closed_psc     = "false"
  region                  = "us-west1"
  target                  = "https://www.googleapis.com/compute/v1/projects/cal-itp-data-infra/regions/us-west1/targetPools/a0d3bb39e959b49a1b6015fd2193e30d"
}

resource "google_compute_forwarding_rule" "tfer--ad40eb3afc69e4deeaf43a1ed1393eeb" {
  all_ports               = "false"
  allow_global_access     = "false"
  allow_psc_global_access = "false"
  description             = "{\"kubernetes.io/service-name\":\"ingress-nginx/ingress-nginx-controller\"}"
  ip_address              = "34.127.51.123"
  ip_protocol             = "TCP"
  is_mirroring_collector  = "false"
  load_balancing_scheme   = "EXTERNAL"
  name                    = "ad40eb3afc69e4deeaf43a1ed1393eeb"
  network_tier            = "PREMIUM"
  port_range              = "80-443"
  project                 = "cal-itp-data-infra"
  recreate_closed_psc     = "false"
  region                  = "us-west1"
  target                  = "https://www.googleapis.com/compute/v1/projects/cal-itp-data-infra/regions/us-west1/targetPools/ad40eb3afc69e4deeaf43a1ed1393eeb"
}
