WITH external_service_by_mode_and_time_period AS (
    SELECT *
    FROM {{ source('external_ntd__annual_reporting', 'multi_year__service_by_mode_and_time_period') }}
),

get_latest_extract AS(
    SELECT *
    FROM external_service_by_mode_and_time_period
    -- we pull the whole table every month in the pipeline, so this gets only the latest extract
    QUALIFY DENSE_RANK() OVER (ORDER BY execution_ts DESC) = 1
),

stg_ntd__service_by_mode_and_time_period AS (
    SELECT
        {{ dbt_utils.generate_surrogate_key(['_5_digit_ntd_id', 'report_year', 'mode', 'type_of_service', 'time_period']) }} AS key,
        {{ trim_make_empty_string_null('_5_digit_ntd_id') }} AS ntd_id,
        PARSE_BIGNUMERIC(actual_vehicles_passenger_car_deadhead_hours) AS actual_vehicles_passenger_car_deadhead_hours,
        PARSE_BIGNUMERIC(actual_vehicles_passenger_car_hours) AS actual_vehicles_passenger_car_hours,
        PARSE_BIGNUMERIC(actual_vehicles_passenger_car_miles) AS actual_vehicles_passenger_car_miles,
        PARSE_BIGNUMERIC(actual_vehicles_passenger_car_revenue_hours) AS actual_vehicles_passenger_car_revenue_hours,
        PARSE_BIGNUMERIC(actual_vehicles_passenger_car_revenue_miles) AS actual_vehicles_passenger_car_revenue_miles,
        PARSE_BIGNUMERIC(actual_vehicles_passenger_deadhead_miles) AS actual_vehicles_passenger_deadhead_miles,
        PARSE_BIGNUMERIC(ada_upt) AS ada_upt,
        {{ trim_make_empty_string_null('agency') }} AS agency,
        PARSE_BIGNUMERIC(agency_voms) AS agency_voms,
        {{ trim_make_empty_string_null('aptl_questionable') }} AS aptl_questionable,
        PARSE_BIGNUMERIC(average_passenger_trip_length_aptl_) AS average_passenger_trip_length_aptl_,
        PARSE_BIGNUMERIC(average_speed) AS average_speed,
        {{ trim_make_empty_string_null('average_speed_questionable') }} AS average_speed_questionable,
        PARSE_BIGNUMERIC(brt_non_statutory_mixed_traffic) AS brt_non_statutory_mixed_traffic,
        {{ trim_make_empty_string_null('city') }} AS city,
        PARSE_BIGNUMERIC(charter_service_hours) AS charter_service_hours,
        PARSE_BIGNUMERIC(days_of_service_operated) AS days_of_service_operated,
        PARSE_BIGNUMERIC(days_not_operated_strikes) AS days_not_operated_strikes,
        PARSE_BIGNUMERIC(days_not_operated_emergencies) AS days_not_operated_emergencies,
        {{ trim_make_empty_string_null('deadhead_hours_questionable') }} AS deadhead_hours_questionable,
        {{ trim_make_empty_string_null('deadhead_miles_questionable') }} AS deadhead_miles_questionable,
        PARSE_BIGNUMERIC(directional_route_miles) AS directional_route_miles,
        {{ trim_make_empty_string_null('directional_route_miles_questionable') }} AS directional_route_miles_questionable,
        PARSE_BIGNUMERIC(mixed_traffic_right_of_way) AS mixed_traffic_right_of_way,
        {{ trim_make_empty_string_null('mode') }} AS mode,
        {{ trim_make_empty_string_null('mode_name') }} AS mode_name,
        PARSE_BIGNUMERIC(mode_voms) AS mode_voms,
        {{ trim_make_empty_string_null('mode_voms_questionable') }} AS mode_voms_questionable,
        {{ trim_make_empty_string_null('organization_type') }} AS organization_type,
        PARSE_BIGNUMERIC(passenger_miles) AS passenger_miles,
        {{ trim_make_empty_string_null('passenger_miles_questionable') }} AS passenger_miles_questionable,
        PARSE_BIGNUMERIC(passengers_per_hour) AS passengers_per_hour,
        {{ trim_make_empty_string_null('passengers_per_hour_questionable') }} AS passengers_per_hour_questionable,
        PARSE_BIGNUMERIC(primary_uza_area_sq_miles) AS primary_uza_area_sq_miles,
        PARSE_BIGNUMERIC(primary_uza_code) AS primary_uza_code,
        {{ trim_make_empty_string_null('primary_uza_name') }} AS primary_uza_name,
        PARSE_BIGNUMERIC(primary_uza_population) AS primary_uza_population,
        PARSE_BIGNUMERIC(report_year AS INT64) AS report_year,
        {{ trim_make_empty_string_null('reporter_type') }} AS reporter_type,
        {{ trim_make_empty_string_null('scheduled_revenue_miles_questionable') }} AS scheduled_revenue_miles_questionable,
        PARSE_BIGNUMERIC(scheduled_vehicles_passenger_car_revenue_miles) AS scheduled_vehicles_passenger_car_revenue_miles,
        PARSE_BIGNUMERIC(school_bus_hours) AS school_bus_hours,
        PARSE_BIGNUMERIC(service_area_population) AS service_area_population,
        PARSE_BIGNUMERIC(service_area_sq_miles) AS service_area_sq_miles,
        PARSE_BIGNUMERIC(sponsored_service_upt) AS sponsored_service_upt,
        {{ trim_make_empty_string_null('state') }} AS state,
        {{ trim_make_empty_string_null('time_period') }} AS time_period,
        {{ trim_make_empty_string_null('time_service_begins') }} AS time_service_begins,
        {{ trim_make_empty_string_null('time_service_ends') }} AS time_service_ends,
        PARSE_BIGNUMERIC(train_deadhead_hours) AS train_deadhead_hours,
        PARSE_BIGNUMERIC(train_deadhead_miles) AS train_deadhead_miles,
        PARSE_BIGNUMERIC(train_hours) AS train_hours,
        {{ trim_make_empty_string_null('train_hours_questionable') }} AS train_hours_questionable,
        PARSE_BIGNUMERIC(trains_in_operation) AS trains_in_operation,
        {{ trim_make_empty_string_null('trains_in_operation_questionable') }} AS trains_in_operation_questionable,
        PARSE_BIGNUMERIC(train_miles) AS train_miles,
        {{ trim_make_empty_string_null('train_miles_questionable') }} AS train_miles_questionable,
        PARSE_BIGNUMERIC(train_revenue_hours) AS train_revenue_hours,
        {{ trim_make_empty_string_null('train_revenue_hours_questionable') }} AS train_revenue_hours_questionable,
        PARSE_BIGNUMERIC(train_revenue_miles) AS train_revenue_miles,
        {{ trim_make_empty_string_null('train_revenue_miles_questionable') }} AS train_revenue_miles_questionable,
        {{ trim_make_empty_string_null('type_of_service') }} AS type_of_service,
        PARSE_BIGNUMERIC(unlinked_passenger_trips_upt) AS unlinked_passenger_trips_upt,
        {{ trim_make_empty_string_null('unlinked_passenger_trips_questionable') }} AS unlinked_passenger_trips_questionable,
        {{ trim_make_empty_string_null('vehicle_hours_questionable') }} AS vehicle_hours_questionable,
        {{ trim_make_empty_string_null('vehicle_miles_questionable') }} AS vehicle_miles_questionable,
        {{ trim_make_empty_string_null('vehicle_revenue_hours_questionable') }} AS vehicle_revenue_hours_questionable,
        {{ trim_make_empty_string_null('vehicle_revenue_miles_questionable') }} AS vehicle_revenue_miles_questionable,
        dt,
        execution_ts
    FROM get_latest_extract
)

SELECT * FROM stg_ntd__service_by_mode_and_time_period
