version: 2

models:
  - name: stg_ntd__fra_regulated_mode_major_security_events
  - name: stg_ntd__major_safety_events
  - name: stg_ntd__monthly_modal_time_series_safety_and_service
  - name: stg_ntd__nonmajor_safety_and_security_events
