WITH stg_ntd__monthly_modal_time_series_safety_and_service AS (
    SELECT *
    FROM {{ source('external_ntd__safety_and_security', 'historical__monthly_modal_time_series_safety_and_service') }}
    -- we pull the whole table every month in the pipeline, so this gets only the latest extract
    QUALIFY DENSE_RANK() OVER (ORDER BY execution_ts DESC) = 1
)

SELECT
    SAFE_CAST(major_non_physical_assaults_on_operators AS NUMERIC) AS major_non_physical_assaults_on_operators,
    SAFE_CAST(major_non_physical_assaults_on_other_transit_workers AS NUMERIC) AS major_non_physical_assaults_on_other_transit_workers,
    SAFE_CAST(major_physical_assaults_on_operators AS NUMERIC) AS major_physical_assaults_on_operators,
    SAFE_CAST(non_major_non_physical_assaults_on_other_transit_workers AS NUMERIC) AS non_major_non_physical_assaults_on_other_transit_workers,
    SAFE_CAST(non_major_physical_assaults_on_other_transit_workers AS NUMERIC) AS non_major_physical_assaults_on_other_transit_workers,
    SAFE_CAST(non_major_non_physical_assaults_on_operators AS NUMERIC) AS non_major_non_physical_assaults_on_operators,
    SAFE_CAST(total_injuries AS NUMERIC) AS total_injuries,
    SAFE_CAST(trespasser_injuries AS NUMERIC) AS trespasser_injuries,
    SAFE_CAST(other_injuries AS NUMERIC) AS other_injuries,
    SAFE_CAST(other_vehicle_occupant AS NUMERIC) AS other_vehicle_occupant,
    SAFE_CAST(other_vehicle_occupant_1 AS NUMERIC) AS other_vehicle_occupant_1,
    SAFE_CAST(pedestrian_walking_along AS NUMERIC) AS pedestrian_walking_along,
    SAFE_CAST(pedestrian_walking_along_1 AS NUMERIC) AS pedestrian_walking_along_1,
    SAFE_CAST(pedestrian_in_corsswalk AS NUMERIC) AS pedestrian_in_corsswalk,
    SAFE_CAST(bicyclist_injuries AS NUMERIC) AS bicyclist_injuries,
    SAFE_CAST(other_worker_injuries AS NUMERIC) AS other_worker_injuries,
    SAFE_CAST(total_employee_injuries AS NUMERIC) AS total_employee_injuries,
    SAFE_CAST(other_employee_injuries AS NUMERIC) AS other_employee_injuries,
    SAFE_CAST(operator_injuries AS NUMERIC) AS operator_injuries,
    SAFE_CAST(total_other_fatalities AS NUMERIC) AS total_other_fatalities,
    SAFE_CAST(people_waiting_or_leaving AS NUMERIC) AS people_waiting_or_leaving,
    SAFE_CAST(people_waiting_or_leaving_1 AS NUMERIC) AS people_waiting_or_leaving_1,
    SAFE_CAST(total_fatalities AS NUMERIC) AS total_fatalities,
    SAFE_CAST(trespasser_fatalities AS NUMERIC) AS trespasser_fatalities,
    SAFE_CAST(suicide_injuries AS NUMERIC) AS suicide_injuries,
    SAFE_CAST(collisions_with_other AS NUMERIC) AS collisions_with_other,
    SAFE_CAST(suicide_fatalities AS NUMERIC) AS suicide_fatalities,
    SAFE_CAST(pedestrian_in_crosswalk AS NUMERIC) AS pedestrian_in_crosswalk,
    SAFE_CAST(bicyclist_fatalities AS NUMERIC) AS bicyclist_fatalities,
    SAFE_CAST(other_worker_fatalities AS NUMERIC) AS other_worker_fatalities,
    {{ trim_make_empty_string_null('type_of_service') }} AS type_of_service,
    {{ trim_make_empty_string_null('mode') }} AS mode,
    SAFE_CAST(passenger_fatalities AS NUMERIC) AS passenger_fatalities,
    SAFE_CAST(total_employee_fatalities AS NUMERIC) AS total_employee_fatalities,
    SAFE_CAST(operator_fatalities AS NUMERIC) AS operator_fatalities,
    {{ trim_make_empty_string_null('CAST(uace_code AS STRING)') }} AS uace_code,
    {{ trim_make_empty_string_null('month') }} AS month,
    SAFE_CAST(total_events_not_otherwise AS NUMERIC) AS total_events_not_otherwise,
    SAFE_CAST(primary_uza_population AS NUMERIC) AS primary_uza_population,
    SAFE_CAST(collisions_with_bus_vehicle AS NUMERIC) AS collisions_with_bus_vehicle,
    SAFE_CAST(total_security_events AS NUMERIC) AS total_security_events,
    SAFE_CAST(total_events AS NUMERIC) AS total_events,
    SAFE_CAST(rail_y_n AS BOOLEAN) AS rail_y_n,
    SAFE_CAST(total_fires AS NUMERIC) AS total_fires,
    SAFE_CAST(total_derailments AS NUMERIC) AS total_derailments,
    SAFE_CAST(total_assaults_on_transit_workers AS NUMERIC) AS total_assaults_on_transit_workers,
    SAFE_CAST(total_collisions AS NUMERIC) AS total_collisions,
    {{ trim_make_empty_string_null('agency') }} AS agency,
    SAFE_CAST(collisions_with_rail_vehicle AS NUMERIC) AS collisions_with_rail_vehicle,
    SAFE_CAST(passenger_injuries AS NUMERIC) AS passenger_injuries,
    SAFE_CAST(collisions_with_fixed_object AS NUMERIC) AS collisions_with_fixed_object,
    SAFE_CAST(ridership AS NUMERIC) AS ridership,
    SAFE_CAST(service_area_population AS NUMERIC) AS service_area_population,
    SAFE_CAST(collisions_with_person AS NUMERIC) AS collisions_with_person,
    SAFE_CAST(major_physical_assaults_on_other_transit_workers AS NUMERIC) AS major_physical_assaults_on_other_transit_workers,
    SAFE_CAST(collisions_with_motor_vehicle AS NUMERIC) AS collisions_with_motor_vehicle,
    SAFE_CAST(service_area_sq_miles AS NUMERIC) AS service_area_sq_miles,
    SAFE_CAST(other_employee_fatalities AS NUMERIC) AS other_employee_fatalities,
    SAFE_CAST(non_major_physical_assaults_on_operators AS NUMERIC) AS non_major_physical_assaults_on_operators,
    SAFE_CAST(year AS INTEGER) AS year,
    SAFE_CAST(vehicle_revenue_hours AS NUMERIC) AS vehicle_revenue_hours,
    SAFE_CAST(vehicle_revenue_miles AS NUMERIC) AS vehicle_revenue_miles,
    SAFE_CAST(vehicles AS NUMERIC) AS vehicles,
    {{ trim_make_empty_string_null('organization_type') }} AS organization_type,
    SAFE_CAST(pedestrian_crossing_tracks AS NUMERIC) AS pedestrian_crossing_tracks,
    SAFE_CAST(pedestrian_crossing_tracks_1 AS NUMERIC) AS pedestrian_crossing_tracks_1,
    SAFE_CAST(primary_uza_sq_miles AS NUMERIC) AS primary_uza_sq_miles,
    {{ trim_make_empty_string_null('primary_uza_name') }} AS primary_uza_name,
    {{ trim_make_empty_string_null('CAST(_5_digit_ntd_id AS STRING)') }} AS ntd_id,
    SAFE_CAST(total_other_injuries AS NUMERIC) AS total_other_injuries,
    SAFE_CAST(other_fatalities AS NUMERIC) AS other_fatalities,
    SAFE_CAST(pedestrian_not_in_crosswalk AS NUMERIC) AS pedestrian_not_in_crosswalk,
    SAFE_CAST(pedestrian_not_in_crosswalk_1 AS NUMERIC) AS pedestrian_not_in_crosswalk_1,
    dt,
    execution_ts
FROM stg_ntd__monthly_modal_time_series_safety_and_service
