WITH external_nonmajor_safety_and_security_events AS (
    SELECT *
    FROM {{ source('external_ntd__safety_and_security', 'historical__nonmajor_safety_and_security_events') }}
),

get_latest_extract AS(
    SELECT *
    FROM external_nonmajor_safety_and_security_events
    -- we pull the whole table every month in the pipeline, so this gets only the latest extract
    QUALIFY DENSE_RANK() OVER (ORDER BY execution_ts DESC) = 1
),

stg_ntd__nonmajor_safety_and_security_events AS (
    SELECT *
    FROM get_latest_extract
)

SELECT
    {{ trim_make_empty_string_null('other_fire_fuel_description') }} AS other_fire_fuel_description,
    {{ trim_make_empty_string_null('operator_location') }} AS operator_location,
    {{ trim_make_empty_string_null('tide') }} AS tide,
    {{ trim_make_empty_string_null('current_condition') }} AS current_condition,
    {{ trim_make_empty_string_null('runaway_train_flag') }} AS runaway_train_flag,
    {{ trim_make_empty_string_null('track_configuration') }} AS track_configuration,
    {{ trim_make_empty_string_null('hazmat_type') }} AS hazmat_type,
    {{ trim_make_empty_string_null('fire_fuel') }} AS fire_fuel,
    {{ trim_make_empty_string_null('fire_type') }} AS fire_type,
    {{ trim_make_empty_string_null('rail_grade_crossing_control') }} AS rail_grade_crossing_control,
    SAFE_CAST(incident_number AS INTEGER) AS incident_number,
    {{ trim_make_empty_string_null('manufacturer') }} AS manufacturer,
    {{ trim_make_empty_string_null('non_rail_transit_vehicle') }} AS non_rail_transit_vehicle,
    SAFE_CAST(derailed_cars_count AS NUMERIC) AS derailed_cars_count,
    {{ trim_make_empty_string_null('fuel_type') }} AS fuel_type,
    {{ trim_make_empty_string_null('transit_y_n') }} AS transit_y_n,
    SAFE_CAST(evacuation AS BOOLEAN) AS evacuation,
    {{ trim_make_empty_string_null('path_condition') }} AS path_condition,
    SAFE_CAST(suicide_fatalities AS INTEGER) AS suicide_fatalities,
    {{ trim_make_empty_string_null('weather') }} AS weather,
    {{ trim_make_empty_string_null('collision_with') }} AS collision_with,
    {{ trim_make_empty_string_null('other_event_type_description') }} AS other_event_type_description,
    SAFE_CAST(total_serious_injuries AS INTEGER) AS total_serious_injuries,
    SAFE_CAST(transit_vehicle_operator_2 AS INTEGER) AS transit_vehicle_operator_2,
    SAFE_CAST(property_damage AS NUMERIC) AS property_damage,
    SAFE_CAST(trespasser_inuries_subtotal_ AS INTEGER) AS trespasser_inuries_subtotal_,
    SAFE_CAST(bicyclist_serious_injuries AS INTEGER) AS bicyclist_serious_injuries,
    SAFE_CAST(suicide_serious_injuries AS INTEGER) AS suicide_serious_injuries,
    SAFE_CAST(transit_vehicle_rider AS INTEGER) AS transit_vehicle_rider,
    SAFE_CAST(other_serious_injuries AS INTEGER) AS other_serious_injuries,
    {{ trim_make_empty_string_null('evacuation_location') }} AS evacuation_location,
    SAFE_CAST(other_injuries AS INTEGER) AS other_injuries,
    SAFE_CAST(occupant_of_other_vehicle_2 AS INTEGER) AS occupant_of_other_vehicle_2,
    SAFE_CAST(pedestrian_walking_along_1 AS INTEGER) AS pedestrian_walking_along_1,
    {{ trim_make_empty_string_null('vehicle_action') }} AS vehicle_action,
    SAFE_CAST(pedestrian_crossing_tracks_1 AS INTEGER) AS pedestrian_crossing_tracks_1,
    {{ trim_make_empty_string_null('hazmat_type_description') }} AS hazmat_type_description,
    SAFE_CAST(pedestrian_not_in_crosswalk_1 AS INTEGER) AS pedestrian_not_in_crosswalk_1,
    SAFE_CAST(pederstiran_in_crosswalk AS INTEGER) AS pederstiran_in_crosswalk,
    SAFE_CAST(__computed_region_8fe2_rd7y AS NUMERIC) AS __computed_region_8fe2_rd7y,
    SAFE_CAST(bicyclist_injuries AS INTEGER) AS bicyclist_injuries,
    {{ trim_make_empty_string_null('_5_digit_ntd_id') }} AS _5_digit_ntd_id,
    SAFE_CAST(transit_employee_serious AS INTEGER) AS transit_employee_serious,
    SAFE_CAST(transit_employee_injuries AS INTEGER) AS transit_employee_injuries,
    SAFE_CAST(trespasser_serious_injuries_subtotal_ AS INTEGER) AS trespasser_serious_injuries_subtotal_,
    SAFE_CAST(transit_vehicle_rider_serious AS INTEGER) AS transit_vehicle_rider_serious,
    SAFE_CAST(intentional_y_n AS BOOLEAN) AS intentional_y_n,
    SAFE_CAST(transit_vehicle_rider_injuries AS INTEGER) AS transit_vehicle_rider_injuries,
    SAFE_CAST(trespasser_fatalities_subtotal_ AS INTEGER) AS trespasser_fatalities_subtotal_,
    SAFE_CAST(other_fatalities AS INTEGER) AS other_fatalities,
    SAFE_CAST(longitude AS NUMERIC) AS longitude,
    SAFE_CAST(occupant_of_other_vehicle AS INTEGER) AS occupant_of_other_vehicle,
    {{ trim_make_empty_string_null('evacuation_comment') }} AS evacuation_comment,
    SAFE_CAST(latitude AS NUMERIC) AS latitude,
    SAFE_CAST(pedestrian_crossing_tracks AS INTEGER) AS pedestrian_crossing_tracks,
    {{ trim_make_empty_string_null('rail_alignment') }} AS rail_alignment,
    SAFE_CAST(pedestrian_in_crosswalk AS INTEGER) AS pedestrian_in_crosswalk,
    {{ trim_make_empty_string_null('safety_security') }} AS safety_security,
    SAFE_CAST(transit_employee_fatalities AS INTEGER) AS transit_employee_fatalities,
    {{ trim_make_empty_string_null('revenue_vehicle_identifier_list') }} AS revenue_vehicle_identifier_list,
    {{ trim_make_empty_string_null('manufacturer_description') }} AS manufacturer_description,
    SAFE_CAST(transit_vehicle_operator AS INTEGER) AS transit_vehicle_operator,
    SAFE_CAST(evac_to_right_of_way AS BOOLEAN) AS evac_to_right_of_way,
    {{ trim_make_empty_string_null('event_type') }} AS event_type,
    SAFE_CAST(total_injuries AS INTEGER) AS total_injuries,
    SAFE_CAST(life_safety_y_n AS BOOLEAN) AS life_safety_y_n,
    latlon,
    {{ trim_make_empty_string_null('lighting') }} AS lighting,
    SAFE_CAST(other_worker_injuries AS INTEGER) AS other_worker_injuries,
    SAFE_CAST(people_waiting_or_leaving_2 AS INTEGER) AS people_waiting_or_leaving_2,
    {{ trim_make_empty_string_null('location_type') }} AS location_type,
    SAFE_CAST(pedestrian_crossing_tracks_2 AS INTEGER) AS pedestrian_crossing_tracks_2,
    SAFE_CAST(bicyclist_fatalities AS INTEGER) AS bicyclist_fatalities,
    SAFE_CAST(number_of_cars_on_involved_transit_vehicles AS INTEGER) AS number_of_cars_on_involved_transit_vehicles,
    SAFE_CAST(number_of_vehicles_involved AS INTEGER) AS number_of_vehicles_involved,
    {{ trim_make_empty_string_null('approximate_address') }} AS approximate_address,
    SAFE_CAST(__computed_region_m2nu_4dib AS NUMERIC) AS __computed_region_m2nu_4dib,
    {{ trim_make_empty_string_null('derailment_type') }} AS derailment_type,
    SAFE_CAST(suicide_injuries AS INTEGER) AS suicide_injuries,
    {{ trim_make_empty_string_null('mode_name') }} AS mode_name,
    SAFE_CAST(pedestrian_walking_along AS INTEGER) AS pedestrian_walking_along,
    SAFE_CAST(assault_homicide_transit_worker_flag AS BOOLEAN) AS assault_homicide_transit_worker_flag,
    {{ trim_make_empty_string_null('action_type') }} AS action_type,
    SAFE_CAST(people_waiting_or_leaving_1 AS INTEGER) AS people_waiting_or_leaving_1,
    {{ trim_make_empty_string_null('property_damage_type') }} AS property_damage_type,
    SAFE_CAST(total_fatalities AS INTEGER) AS total_fatalities,
    {{ trim_make_empty_string_null('road_configuration') }} AS road_configuration,
    SAFE_CAST(self_evacuation_y_n AS BOOLEAN) AS self_evacuation_y_n,
    SAFE_CAST(incident_time AS INTEGER) AS incident_time,
    {{ trim_make_empty_string_null('person_list') }} AS person_list,
    {{ trim_make_empty_string_null('type_of_service') }} AS type_of_service,
    SAFE_CAST(vehicle_speed AS NUMERIC) AS vehicle_speed,
    {{ trim_make_empty_string_null('mode') }} AS mode,
    SAFE_CAST(other_worker_serious_injuries AS INTEGER) AS other_worker_serious_injuries,
    {{ trim_make_empty_string_null('rail_bus_ferry') }} AS rail_bus_ferry,
    SAFE_CAST(transit_vehicle_operator_1 AS INTEGER) AS transit_vehicle_operator_1,
    SAFE_CAST(people_waiting_or_leaving AS INTEGER) AS people_waiting_or_leaving,
    SAFE_CAST(pedestrian_not_in_crosswalk_2 AS INTEGER) AS pedestrian_not_in_crosswalk_2,
    SAFE_CAST(fixed_route_flag AS BOOLEAN) AS fixed_route_flag,
    {{ trim_make_empty_string_null('event_category') }} AS event_category,
    {{ trim_make_empty_string_null('assault_homicide_type_desc') }} AS assault_homicide_type_desc,
    {{ trim_make_empty_string_null('event_type_group') }} AS event_type_group,
    SAFE_CAST(other_worker_fatalities AS INTEGER) AS other_worker_fatalities,
    {{ trim_make_empty_string_null('incident_description') }} AS incident_description,
    SAFE_CAST(pederstiran_in_crosswalk_1 AS INTEGER) AS pederstiran_in_crosswalk_1,
    {{ trim_make_empty_string_null('assault_homicide_person_type_desc') }} AS assault_homicide_person_type_desc,
    {{ trim_make_empty_string_null('service_stop_control_device') }} AS service_stop_control_device,
    incident_date,
    SAFE_CAST(pedestrian_walking_along_2 AS INTEGER) AS pedestrian_walking_along_2,
    SAFE_CAST(towed_y_n AS BOOLEAN) AS towed_y_n,
    {{ trim_make_empty_string_null('agency') }} AS agency,
    {{ trim_make_empty_string_null('intersection') }} AS intersection,
    SAFE_CAST(occupant_of_other_vehicle_1 AS INTEGER) AS occupant_of_other_vehicle_1,
    SAFE_CAST(pedestrian_not_in_crosswalk AS INTEGER) AS pedestrian_not_in_crosswalk,
    {{ trim_make_empty_string_null('right_of_way_condition') }} AS right_of_way_condition,
    SAFE_CAST(number_of_transit_vehicles AS INTEGER) AS number_of_transit_vehicles,
    SAFE_CAST(year AS INTEGER) AS year,
    SAFE_CAST(uace_code AS INTEGER) AS uace_code,
    dt,
    execution_ts
FROM stg_ntd__nonmajor_safety_and_security_events
