#!/bin/bash

# script/docs-server: Launch mkdocs server to preview live work on docs/

set -e
cd "$(dirname "$0")/.."


echo
echo "Initializing venv..."
python -m venv .mkdocs-venv
source .mkdocs-venv/bin/activate
pip install --upgrade pip


echo
echo "Installing mkdocs and plugins..."
# lines after mkdocs and mkdocs-material are optional plugins,
# must be matched in .holo/branches/docs-site.lenses/mkdocs.toml
pip install \
    mkdocs==1.1.2 \
    mkdocs-material \
    mkdocs-awesome-pages-plugin \
    fontawesome_markdown \
    mkdocs-macros-plugin


echo
echo "Starting mkdocs server..."
mkdocs serve --dev-addr "0.0.0.0:8000"
