apiVersion: v1
kind: ConfigMap
metadata:
  name: archiver-channel-vars
data:
  AIRFLOW_ENV: development
  CALITP_BUCKET__GTFS_CONFIG: "gs://test-calitp-gtfs-download-config"
  CALITP_BUCKET__GTFS_RT_RAW: "gs://test-calitp-gtfs-rt-raw-v2"
  HUEY_CONSUMER_WORKERS: "12"
