version: 2

models:
  - name: fct_fra_regulated_mode_major_security_events
  - name: fct_major_safety_events
  - name: fct_monthly_modal_time_series_safety_and_service
  - name: fct_nonmajor_safety_and_security_events
