WITH staging_major_safety_events AS (
    SELECT *
    FROM {{ ref('stg_ntd__major_safety_events') }}
),

dim_agency_information AS (
    SELECT
        ntd_id,
        year,
        agency_name,
        city,
        state,
        caltrans_district_current,
        caltrans_district_name_current
    FROM {{ ref('dim_agency_information') }}
),

fct_major_safety_events AS (
    SELECT
        stg.key,
        stg.ntd_id,
        stg.year,

        agency.agency_name,
        agency.city,
        agency.state,
        agency.caltrans_district_current,
        agency.caltrans_district_name_current,

        stg.agency AS source_agency,
        stg.uace_code,
        stg.rail_bus_ferry,
        stg.mode_name,
        stg.mode,
        stg.type_of_service,
        stg.fixed_route_flag,
        stg.incident_description,
        stg.incident_number,
        stg.incident_date,
        stg.incident_time,
        stg.event_type,
        stg.event_type_group,
        stg.assault_homicide_person_type_desc,
        stg.assault_homicide_type_desc,
        stg.assault_homicide_transit_worker_flag,
        stg.event_category,
        stg.safety_security,
        stg.property_damage,
        stg.total_injuries,
        stg.total_fatalities,
        stg.towed_y_n,
        stg.number_of_transit_vehicles,
        stg.number_of_vehicles_involved,
        stg.number_of_cars_on_involved_transit_vehicles,
        stg.location_type,
        stg.approximate_address,
        stg.latitude,
        stg.longitude,
        stg.latlon,
        stg.evacuation,
        stg.life_safety_y_n,
        stg.evac_to_right_of_way,
        stg.self_evacuation_y_n,
        stg.intentional_y_n,
        stg.transit_vehicle_rider,
        stg.people_waiting_or_leaving,
        stg.transit_vehicle_operator,
        stg.transit_employee_fatalities,
        stg.other_worker_fatalities,
        stg.bicyclist_fatalities,
        stg.pedestrian_in_crosswalk,
        stg.pedestrian_not_in_crosswalk,
        stg.pedestrian_crossing_tracks,
        stg.pedestrian_walking_along,
        stg.occupant_of_other_vehicle,
        stg.other_fatalities,
        stg.suicide_fatalities,
        stg.trespasser_fatalities_subtotal_,
        stg.transit_vehicle_rider_injuries,
        stg.transit_vehicle_rider_serious,
        stg.people_waiting_or_leaving_1,
        stg.people_waiting_or_leaving_2,
        stg.transit_vehicle_operator_1,
        stg.transit_vehicle_operator_2,
        stg.transit_employee_injuries,
        stg.transit_employee_serious,
        stg.other_worker_injuries,
        stg.other_worker_serious_injuries,
        stg.bicyclist_injuries,
        stg.bicyclist_serious_injuries,
        stg.pederstiran_in_crosswalk,
        stg.pederstiran_in_crosswalk_1,
        stg.pedestrian_not_in_crosswalk_1,
        stg.pedestrian_not_in_crosswalk_2,
        stg.pedestrian_crossing_tracks_1,
        stg.pedestrian_crossing_tracks_2,
        stg.pedestrian_walking_along_1,
        stg.pedestrian_walking_along_2,
        stg.occupant_of_other_vehicle_1,
        stg.occupant_of_other_vehicle_2,
        stg.other_injuries,
        stg.other_serious_injuries,
        stg.suicide_injuries,
        stg.suicide_serious_injuries,
        stg.trespasser_inuries_subtotal_,
        stg.trespasser_serious_injuries_subtotal_,
        stg.total_serious_injuries,
        stg.computed_region_m2nu_4dib,
        stg.computed_region_8fe2_rd7y,
        stg.person_list,
        stg.evacuation_comment,
        stg.evacuation_location,
        stg.other_event_type_description,
        stg.collision_with,
        stg.other_vehicle_type_list,
        stg.weather,
        stg.lighting,
        stg.road_configuration,
        stg.path_condition,
        stg.right_of_way_condition,
        stg.vehicle_action,
        stg.action_type,
        stg.non_transit_vehicle_action_list,
        stg.transit_y_n,
        stg.revenue_vehicle_identifier_list,
        stg.fuel_type,
        stg.vehicle_speed,
        stg.transit_vehicle_type,
        stg.non_rail_transit_vehicle,
        stg.manufacturer,
        stg.manufacturer_description,
        stg.fire_type,
        stg.fire_fuel,
        stg.property_damage_type,
        stg.rail_grade_crossing_control,
        stg.intersection,
        stg.multiple_locations_list,
        stg.derailed_cars_count,
        stg.rail_alignment,
        stg.rail_grade_crossing_comment,
        stg.track_configuration,
        stg.derailment_type,
        stg.runaway_train_flag,
        stg.operator_location,
        stg.service_stop_control_device,
        stg.current_condition,
        stg.tide,
        stg.weather_comment,
        stg.hazmat_type,
        stg.dt,
        stg.execution_ts
    FROM staging_major_safety_events AS stg
    LEFT JOIN dim_agency_information AS agency
        ON stg.ntd_id = agency.ntd_id
            AND stg.year = agency.year
)

SELECT * FROM fct_major_safety_events
