WITH staging_fra_regulated_mode_major_security_events AS (
    SELECT *
    FROM {{ ref('stg_ntd__fra_regulated_mode_major_security_events') }}
),

current_dim_organizations AS (
    SELECT
        ntd_id,
        caltrans_district AS caltrans_district_current,
        caltrans_district_name AS caltrans_district_name_current
    FROM {{ ref('dim_organizations_latest_with_caltrans_district') }}
),

fct_fra_regulated_mode_major_security_events AS (
    SELECT
        stg.other_vehicle_action,
        stg.manufacturer_description,
        stg.evacuation_comment,
        stg.manufacturer,
        stg.non_rail_transit_vehicle,
        stg.fuel_type,
        stg.transit_y_n,
        stg.evacuation_location,
        stg.rail_alignment,
        stg.path_condition,
        stg.weather,
        stg.collision_with,
        stg.fire_type,
        stg.suicide_serious_injuries,
        stg.other_serious_injuries,
        stg.other_injuries,
        stg.occupant_of_other_vehicle_2,
        stg.other_involved_veh,
        stg.vehicle_speed,
        stg.occupant_of_other_vehicle_1,
        stg.pedestrian_walking_along_1,
        stg.vehicle_action,
        stg.pedestrian_crossing_tracks_1,
        stg.pedestrian_not_in_crosswalk_1,
        stg.pedestrian_in_crosswalk_2,
        stg.pedestrian_in_crosswalk_1,
        stg.rail_bus_ferry,
        stg.people_waiting_or_leaving,
        stg.other_worker_serious_injuries,
        stg.transit_employee_injuries,
        stg.configuration,
        stg.transit_vehicle_rider_serious,
        stg.longitude,
        stg.occupant_of_other_vehicle,
        stg.pedestrian_crossing_tracks,
        stg.latitude,
        stg.lighting,
        stg.people_waiting_or_leaving_2,
        stg.other_worker_injuries,
        stg.transit_vehicle_rider_injuries,
        stg.suicide_fatalities,
        stg.transit_vehicle_rider,
        stg.pedestrian_in_crosswalk,
        stg.action_type,
        stg.bicyclist_serious_injuries,
        stg.total_fatalities,
        stg.people_waiting_or_leaving_1,
        stg.pedestrian_crossing_tracks_2,
        stg.bicyclist_fatalities,
        stg.safety_security,
        stg.transit_employee_fatalities,
        stg.transit_vehicle_operator,
        stg.property_damage_type,
        stg.transit_employee_serious,
        stg.rail_grade_crossing_control,
        stg.intentional_y_n,
        stg.total_injuries,
        stg.event_type,
        stg.event_location,
        stg.number_of_vehicles_involved,
        stg.suicide_injuries,
        stg.pedestrian_walking_along,
        stg.person_list,
        stg.type_of_service,
        stg.mode,
        stg.self_evacuation_y_n,
        stg.bicyclist_injuries,
        stg.property_damage,
        stg.pedestrian_not_in_crosswalk_2,
        stg.fixed_route_flag,
        stg.transit_vehicle_operator_1,
        stg.incident_description,
        stg.incident_date,
        stg.approximate_address,
        stg.other_worker_fatalities,
        stg.incident_time,
        stg.pedestrian_walking_along_2,
        stg.towed_y_n,
        stg.agency,
        stg.right_of_way_condition,
        stg.fire_fuel,
        stg.number_of_transit_vehicles,
        stg.year,
        stg.transit_vehicle_operator_2,
        stg.incident_number,
        stg.other_fatalities,
        stg.pedestrian_not_in_crosswalk,
        stg.number_of_derailed_cars,
        stg.ntd_id,

        orgs.caltrans_district_current,
        orgs.caltrans_district_name_current,

        stg.dt,
        stg.execution_ts
    FROM staging_fra_regulated_mode_major_security_events AS stg
    LEFT JOIN current_dim_organizations AS orgs USING (ntd_id)
)

SELECT * FROM fct_fra_regulated_mode_major_security_events
