name: Build and push sentry-error-loader image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-sentry-error-loader-image.yml'
      - 'jobs/sentry-error-loader/**'
  pull_request:
    paths:
      - '.github/workflows/build-sentry-error-loader-image.yml'
      - 'jobs/sentry-error-loader/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run static checkers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: curl -sSL https://install.python-poetry.org | python -
      - run: cd jobs/sentry-error-loader && poetry install && poetry run mypy .

  build_push:
    name: Package docker image
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: jobs/sentry-error-loader
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{github.repository}}/sentry-error-loader:latest
