name: Build and push gtfs-rt-parser image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-gtfs-rt-parser-image.yml'
      - 'jobs/gtfs-rt-parser/**'

jobs:
  build_push:
    name: Package docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: jobs/gtfs-rt-parser
          push: true
          tags: ghcr.io/${{github.repository}}/gtfs-rt-parser:latest
