name: Build and push gtfs-rt-parser image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-gtfs-rt-parser-image.yml'
      - 'jobs/gtfs-rt-parser/**'
  pull_request:
    paths:
      - '.github/workflows/build-gtfs-rt-parser-image.yml'
      - 'jobs/gtfs-rt-parser/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Package docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: jobs/gtfs-rt-parser
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{github.repository}}/gtfs-rt-parser:latest
