name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'airflow/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Push Airflow code to GCS
        run: |
          gsutil -m rsync -d -c -r airflow/dags gs://$AIRFLOW_BUCKET/dags
          gsutil -m rsync -d -c -r airflow/plugins gs://$AIRFLOW_BUCKET/plugins
        env:
          AIRFLOW_BUCKET: "us-west2-calitp-airflow2-pr-171e4e47-bucket"
