name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'airflow/*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate Google Service Account
        uses: google-github-actions/auth@v2
        with:
          project_id: cal-itp-data-infra
          workload_identity_provider: projects/1005246706141/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: github-actions-terraform@cal-itp-data-infra.iam.gserviceaccount.com

      - name: Setup GCloud utilities
        uses: google-github-actions/setup-gcloud@v2

      - name: Push Airflow code to GCS
        run: |
          gsutil -m rsync -d -c -r airflow/dags gs://us-west2-calitp-airflow2-pr-88ca8ec6-bucket/dags
          gsutil -m rsync -d -c -r airflow/plugins gs://us-west2-calitp-airflow2-pr-88ca8ec6-bucket/plugins
