name: Deploy Airflow Requirements

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-airflow-requirements.yml
      - airflow/requirements.txt

env:
  SERVICE_ACCOUNT: 'github-actions-service-account@cal-itp-data-infra.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/1005246706141/locations/global/workloadIdentityPools/github-actions/providers/data-infra'
  PROJECT_ID: 'cal-itp-data-infra'
  COMPOSER_ENVIRONMENT: 'calitp-airflow2-prod-composer2-20250402'
  COMPOSER_REGION: us-west2

jobs:
  sync:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate Google Service Account
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: 'true'
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup GCloud utilities
        uses: google-github-actions/setup-gcloud@v2

      - name: Update Composer Dependencies
        run: |
          gcloud composer environments update ${{ env.COMPOSER_ENVIRONMENT }} \
          --update-pypi-packages-from-file airflow/requirements.txt \
          --location ${{ env.COMPOSER_REGION }} \
          --project ${{ env.PROJECT_ID }}
