name: Deploy Airflow DAGs

on:
  push:
    paths:
      - 'airflow/**'
  pull_request:
    paths:
      - 'airflow/**'

env:
  USE_GKE_GCLOUD_AUTH_PLUGIN: True

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          install_components: 'gke-gcloud-auth-plugin'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Setup kubeconfig
        env:
          CLOUDSDK_CORE_PROJECT: cal-itp-data-infra
        run: |
          source "$GITHUB_WORKSPACE/kubernetes/gke/config-cluster.sh"
          gcloud container clusters get-credentials "$GKE_NAME" --region "$GKE_REGION"

      - name: Push Airflow code to GCS
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          gsutil -m rsync -d -c -r airflow/dags gs://$AIRFLOW_BUCKET/dags
          gsutil -m rsync -d -c -r airflow/plugins gs://$AIRFLOW_BUCKET/plugins
          gsutil -m rsync -d -c -r airflow/data gs://$AIRFLOW_BUCKET/data
        env:
          AIRFLOW_BUCKET: "us-west2-calitp-airflow2-pr-171e4e47-bucket"
