# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Install Dependencies and Run Pytest on PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f warehouse/requirements.txt ]; then pip install -r warehouse/requirements.txt; fi
        if [ -f script/requirements.txt ]; then pip install -r script/requirements.txt; fi
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
        if [ -f airflow/requirements.txt ]; then pip install -r airflow/requirements.txt; fi
        if [ -f images/jupyter-singleuser/requirements.txt ]; then pip install -r images/jupyter-singleuser/requirements.txt; fi
        if [ -f images/dask/requirements.txt ]; then pip install -r images/dask/requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
