name: Terraform Validation

on:
  pull_request:
    paths:
      - 'iac/*'

jobs:
  targets:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.ls.outputs.paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Discover Terraform targets
        id: ls
        run: echo "paths=$(ls -d iac/*/*/* | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}

  validate:
    needs: targets

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.targets.outputs.paths) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'cal-itp-data-infra'
          workload_identity_provider: 'projects/1005246706141/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Formatting
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.path }}

      - name: Terraform Validation
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.path }}

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add_github_comment: changes-only
          path: ${{ matrix.path }}
