name: Terraform Plan

on:
  pull_request:
    paths:
      - 'iac/**'

jobs:
  targets:
    name: Find targets
    runs-on: ubuntu-latest

    outputs:
      staging: ${{ steps.staging-changes.outputs.all_changed_files }}
      production: ${{ steps.production-changes.outputs.all_changed_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@v46
        id: staging-changes
        with:
          matrix: true
          dir_names: true
          files: 'iac/cal-itp-data-infra-staging/**'

      - uses: tj-actions/changed-files@v46
        id: production-changes
        with:
          matrix: true
          dir_names: true
          files: 'iac/cal-itp-data-infra/**'

  staging:
    name: Staging
    needs: [targets]
    if: ${{ needs.targets.outputs.staging != '[]' && needs.targets.outputs.staging != '' }}
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.targets.outputs.staging) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: 'true'
          project_id: cal-itp-data-infra-staging
          workload_identity_provider: 'projects/473674835135/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-terraform@cal-itp-data-infra-staging.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Formatting
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.path }}

      - name: Terraform Validation
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.path }}

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add_github_comment: changes-only
          path: ${{ matrix.path }}

  production:
    name: Production
    needs: [targets]
    if: ${{ needs.targets.outputs.production != '[]' && needs.targets.outputs.production != '' }}
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.targets.outputs.production) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: 'true'
          project_id: cal-itp-data-infra
          workload_identity_provider: 'projects/1005246706141/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-terraform@cal-itp-data-infra.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Format Check
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.path }}

      - name: Terraform Validate
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.path }}

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add_github_comment: changes-only
          path: ${{ matrix.path }}
