name: Terraform Validation

on:
  pull_request:
    paths:
      - 'iac/*'

jobs:
  targets:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.ls.outputs.paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Discover Terraform targets
        id: ls
        run: echo "paths=$(ls -d iac/*/*/* | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}

  lint:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        path: ${{ fromJson(needs.targets.outputs.paths) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Formatting
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.path }}

  validate:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        path: ${{ fromJson(needs.targets.outputs.paths) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Validation
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.path }}

  plan:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        path: ${{ fromJson(needs.targets.outputs.paths) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo ${{ matrix.path }}

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ${{ matrix.path }}
